name: Slack Notify
description: Send a notification to a Slack channel.

inputs:
  MESSAGE:
    required: true
  SLACK_TOKEN:
    required: true
  SLACK_CHANNELS:
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
            SLACK_CHANNELS_ARRAY=(`echo ${{ inputs.SLACK_CHANNELS }} | sed 's/,/\n/g'`)
            SLACK_BOT_NAME="ElementorBot"
            for CHANNEL in "${SLACK_CHANNELS_ARRAY[@]}"
            do
              curl -X POST "https://slack.com/api/chat.postMessage" -d "username=${SLACK_BOT_NAME}&token=${{ inputs.SLACK_TOKEN }}&channel=${CHANNEL}&text=${{ inputs.MESSAGE }}&link_names=true"
            done
