<?php
namespace Elementor\Core\App\Modules\KitLibrary\Data;

use Elementor\Core\App\Modules\KitLibrary\Data\Exceptions\Api_Response_Exception;
use Elementor\Core\App\Modules\KitLibrary\Data\Exceptions\Kit_Not_Found_Exception;
use Elementor\Data\Base\Controller as Controller_Base;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

class Kits_Controller extends Controller_Base {
	/**
	 * @var Repository
	 */
	public $repository;

	/**
	 * @param \WP_REST_Request $request
	 *
	 * @return \WP_Error|\WP_REST_Response
	 */
	public function get_items( $request ) {
		try {
			$data = $this->repository->get_all(
				get_current_user_id(),
				$request->get_param( 'force' )
			);
		} catch ( Api_Response_Exception $exception ) {
			return new \WP_Error( 'http_response_error', __( 'Connection error.', 'elementor' ) );
		} catch ( \Exception $exception ) {
			return new \WP_Error( 'server_error', __( 'Something went wrong.', 'elementor' ) );
		}

		return new \WP_REST_Response( [
			'data' => $data->all(),
		] );
	}

	/**
	 * @param \WP_REST_Request $request
	 *
	 * @return \WP_Error|\WP_REST_Response
	 */
	public function get_item( $request ) {
		try {
			$data = $this->repository->find(
				$request->get_param( 'id' ),
				get_current_user_id()
			);
		} catch ( Api_Response_Exception $exception ) {
			return new \WP_Error( 'http_response_error', __( 'Connection error.', 'elementor' ), [ 'status' => 500 ] );
		} catch ( Kit_Not_Found_Exception $exception ) {
			return new \WP_Error( 'not_found', $exception->getMessage(), [ 'status' => $exception->getCode() ] );
		} catch ( \Exception $exception ) {
			return new \WP_Error( 'server_error', __( 'Something went wrong.', 'elementor' ), [ 'status' => 500 ] );
		}

		return new \WP_REST_Response( [
			'data' => $data,
		] );
	}

	/**
	 * @return string
	 */
	public function get_name() {
		return 'kits';
	}

	/**
	 * Must implement.
	 */
	public function register_endpoints() {
		$this->register_endpoint( Endpoints\Kits_Favorites::class );
	}

	/**
	 * Register internal endpoint.
	 */
	protected function register_internal_endpoints() {
		// Register as internal to remove the default endpoint generated by the base controller.
		$this->register_endpoint( Endpoints\Kits_Index::class );
	}

	/**
	 * Kits_Controller constructor.
	 *
	 * @param Repository $repository
	 */
	public function __construct( Repository $repository ) {
		parent::__construct();

		$this->repository = $repository;
	}
}
