name: "🚀 Feature Request"
description: "Suggest an idea for this project"
labels: ["status/awaiting_triage"]
body:
  - type: markdown
    attributes:
      value: |
        Before opening a new issue, please search for similar issues to prevent opening a duplicate feature request.
        If there is already an open existing request, please leave a comment there.

        ## The Feature
  - type: checkboxes
    id: prerequisites
    attributes:
      label: "Prerequisites"
      options:
        - label: "I have searched for similar features requests in both open and closed tickets and cannot find a duplicate."
          required: true
        - label: "The feature is still missing in the latest stable version of Elementor ( Elementor Pro )"
          required: true
  - type: textarea
    id: the_problem
    validations:
      required: true
    attributes:
      label: "What problem is your feature request going to solve? Please describe."
      description: "A clear and concise description of what the problem is."
      placeholder: "I'm always frustrated when ..."
  - type: textarea
    id: the_solution
    validations:
      required: true
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen."
      placeholder: "It would be nice if ..."
  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
      placeholder: "I can also be solved by ..."
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here."
      placeholder: "N.B ..."
