import { type ObjectPropType, type PropsSchema, type UnionPropType } from '../../types';

const _STRING_PROP_TYPE = {
	kind: 'string',
	key: 'string',
	settings: {},
	default: null,
	meta: {},
	dependencies: undefined,
	initial_value: null,
};

export const STUBS = {
	tag: {
		kind: 'string',
		key: 'string',
		settings: {},
		default: null,
		meta: {},
		dependencies: undefined,
		initial_value: null,
	},
	color: {
		kind: 'union',
		default: null,
		meta: {
			description: 'A color value prop type',
		},
		settings: {
			required: true,
		},
		prop_types: {
			color: {
				kind: 'string',
				key: 'color',
				default: null,
				meta: {},
				settings: {
					required: true,
				},
				dependencies: undefined,
				initial_value: {
					$$type: 'color',
					value: 'rgba(0, 0, 0, 1)',
				},
			},
			'global-color-variable': {
				kind: 'string',
				key: 'global-color-variable',
				default: null,
				meta: {},
				settings: {},
				dependencies: undefined,
				initial_value: null,
			},
		},
		dependencies: undefined,
		initial_value: {
			$$type: 'color',
			value: 'rgba(0, 0, 0, 1)',
		},
	},
	alignContent: {
		kind: 'string',
		key: 'string',
		default: null,
		meta: {
			description:
				"Aligns a flex container's lines within when there is extra space in the cross-axis. CSS values: center, start, end, space-between, space-around, space-evenly",
		},
		settings: {
			enum: [ 'center', 'start', 'end', 'space-between', 'space-around', 'space-evenly' ],
		},
		dependencies: undefined,
		initial_value: null,
	},
	background: {
		kind: 'object',
		key: 'background',
		default: null,
		meta: {},
		settings: {},
		shape: {
			'background-overlay': {
				kind: 'array',
				key: 'background-overlay',
				default: null,
				meta: {},
				settings: {},
				item_prop_type: {
					kind: 'union',
					default: null,
					meta: [],
					settings: [],
					prop_types: {
						'background-color-overlay': {
							kind: 'object',
							key: 'background-color-overlay',
							default: null,
							meta: {},
							settings: {},
							shape: {
								color: {
									kind: 'union',
									default: null,
									meta: [],
									settings: [],
									prop_types: {
										color: {
											kind: 'string',
											key: 'color',
											default: null,
											meta: {},
											settings: {},
											dependencies: null,
											initial_value: {
												$$type: 'color',
												value: '#00000033',
											},
										},
										'global-color-variable': {
											kind: 'string',
											key: 'global-color-variable',
											default: null,
											meta: {},
											settings: {},
											dependencies: null,
											initial_value: null,
										},
									},
									dependencies: null,
									initial_value: null,
								},
							},
							dependencies: null,
							initial_value: null,
						},
						'background-image-overlay': {
							kind: 'object',
							key: 'background-image-overlay',
							default: null,
							meta: {},
							settings: {},
							shape: {
								image: {
									kind: 'object',
									key: 'image',
									default: null,
									meta: {},
									settings: {},
									shape: {
										src: {
											kind: 'union',
											default: null,
											meta: [],
											settings: [],
											prop_types: {
												'image-src': {
													kind: 'object',
													key: 'image-src',
													default: null,
													meta: {},
													settings: {
														required: true,
													},
													shape: {
														id: {
															kind: 'union',
															default: null,
															meta: [],
															settings: [],
															prop_types: {
																'image-attachment-id': {
																	kind: 'number',
																	key: 'image-attachment-id',
																	default: null,
																	meta: {
																		description:
																			'The ID of the image attachment in the WordPress media library, applicable for internal images only',
																	},
																	settings: {},
																	dependencies: null,
																	initial_value: null,
																},
																dynamic: {
																	kind: 'plain',
																	key: 'dynamic',
																	default: null,
																	meta: {},
																	settings: {
																		categories: [ 'number' ],
																	},
																	dependencies: null,
																	initial_value: null,
																},
															},
															dependencies: null,
															initial_value: null,
														},
														url: {
															kind: 'union',
															default: null,
															meta: [],
															settings: [],
															prop_types: {
																url: {
																	kind: 'string',
																	key: 'url',
																	default: null,
																	meta: {},
																	settings: {},
																	dependencies: null,
																	initial_value: null,
																},
																dynamic: {
																	kind: 'plain',
																	key: 'dynamic',
																	default: null,
																	meta: {},
																	settings: {
																		categories: [ 'url' ],
																	},
																	dependencies: null,
																	initial_value: null,
																},
															},
															dependencies: null,
															initial_value: null,
														},
													},
													dependencies: null,
													initial_value: null,
												},
												dynamic: {
													kind: 'plain',
													key: 'dynamic',
													default: null,
													meta: {},
													settings: {
														categories: [ 'image' ],
													},
													dependencies: null,
													initial_value: null,
												},
											},
											dependencies: null,
											initial_value: null,
										},
										size: {
											kind: 'string',
											key: 'string',
											default: null,
											meta: {
												description:
													"The image file size to use, affecting quality only!. This DOES NOT affect dimensions on the page. For affecting dimensions, use the element's style schema instead",
											},
											settings: {
												enum: [
													'thumbnail',
													'medium',
													'medium_large',
													'large',
													'1536x1536',
													'2048x2048',
													'full',
												],
												required: true,
											},
											dependencies: null,
											initial_value: {
												$$type: 'string',
												value: 'large',
											},
										},
									},
									dependencies: null,
									initial_value: null,
								},
								repeat: {
									kind: 'string',
									key: 'string',
									default: null,
									meta: {},
									settings: {
										enum: [ 'repeat', 'repeat-x', 'repeat-y', 'no-repeat' ],
									},
									dependencies: null,
									initial_value: null,
								},
								size: {
									kind: 'union',
									default: null,
									meta: [],
									settings: [],
									prop_types: {
										string: {
											kind: 'string',
											key: 'string',
											default: null,
											meta: {},
											settings: {
												enum: [ 'auto', 'cover', 'contain' ],
											},
											dependencies: null,
											initial_value: null,
										},
										'background-image-size-scale': {
											kind: 'object',
											key: 'background-image-size-scale',
											default: null,
											meta: {},
											settings: {},
											shape: {
												width: {
													kind: 'union',
													default: null,
													meta: [],
													settings: [],
													prop_types: {
														size: {
															kind: 'object',
															key: 'size',
															default: null,
															meta: {},
															settings: {
																available_units: [
																	'px',
																	'em',
																	'rem',
																	'vw',
																	'vh',
																	'ch',
																	'%',
																	'auto',
																],
															},
															shape: {
																unit: {
																	kind: 'string',
																	key: 'string',
																	default: null,
																	meta: {},
																	settings: {
																		enum: [
																			'px',
																			'em',
																			'rem',
																			'vw',
																			'vh',
																			'ch',
																			'%',
																			'auto',
																			'deg',
																			'rad',
																			'grad',
																			'turn',
																			's',
																			'ms',
																			'auto',
																			'custom',
																			'vmin',
																			'vmax',
																		],
																		required: true,
																	},
																	dependencies: null,
																	initial_value: null,
																},
																size: {
																	kind: 'union',
																	default: null,
																	meta: [],
																	settings: [],
																	prop_types: {
																		string: {
																			kind: 'string',
																			key: 'string',
																			default: null,
																			meta: {},
																			settings: {},
																			dependencies: null,
																			initial_value: null,
																		},
																		number: {
																			kind: 'number',
																			key: 'number',
																			default: null,
																			meta: {},
																			settings: {},
																			dependencies: null,
																			initial_value: null,
																		},
																		dynamic: {
																			kind: 'plain',
																			key: 'dynamic',
																			default: null,
																			meta: {},
																			settings: {
																				categories: [ 'text', 'number' ],
																			},
																			dependencies: null,
																			initial_value: null,
																		},
																	},
																	dependencies: null,
																	initial_value: null,
																},
															},
															dependencies: null,
															initial_value: null,
														},
														'global-size-variable': {
															kind: 'string',
															key: 'global-size-variable',
															default: null,
															meta: {},
															settings: {},
															dependencies: null,
															initial_value: null,
														},
													},
													dependencies: null,
													initial_value: null,
												},
												height: {
													kind: 'union',
													default: null,
													meta: [],
													settings: [],
													prop_types: {
														size: {
															kind: 'object',
															key: 'size',
															default: null,
															meta: {},
															settings: {
																available_units: [
																	'px',
																	'em',
																	'rem',
																	'vw',
																	'vh',
																	'ch',
																	'%',
																	'auto',
																],
															},
															shape: {
																unit: {
																	kind: 'string',
																	key: 'string',
																	default: null,
																	meta: {},
																	settings: {
																		enum: [
																			'px',
																			'em',
																			'rem',
																			'vw',
																			'vh',
																			'ch',
																			'%',
																			'auto',
																			'deg',
																			'rad',
																			'grad',
																			'turn',
																			's',
																			'ms',
																			'auto',
																			'custom',
																			'vmin',
																			'vmax',
																		],
																		required: true,
																	},
																	dependencies: null,
																	initial_value: null,
																},
																size: {
																	kind: 'union',
																	default: null,
																	meta: [],
																	settings: [],
																	prop_types: {
																		string: {
																			kind: 'string',
																			key: 'string',
																			default: null,
																			meta: {},
																			settings: {},
																			dependencies: null,
																			initial_value: null,
																		},
																		number: {
																			kind: 'number',
																			key: 'number',
																			default: null,
																			meta: {},
																			settings: {},
																			dependencies: null,
																			initial_value: null,
																		},
																		dynamic: {
																			kind: 'plain',
																			key: 'dynamic',
																			default: null,
																			meta: {},
																			settings: {
																				categories: [ 'text', 'number' ],
																			},
																			dependencies: null,
																			initial_value: null,
																		},
																	},
																	dependencies: null,
																	initial_value: null,
																},
															},
															dependencies: null,
															initial_value: null,
														},
														'global-size-variable': {
															kind: 'string',
															key: 'global-size-variable',
															default: null,
															meta: {},
															settings: {},
															dependencies: null,
															initial_value: null,
														},
													},
													dependencies: null,
													initial_value: null,
												},
											},
											dependencies: null,
											initial_value: null,
										},
									},
									dependencies: null,
									initial_value: null,
								},
								position: {
									kind: 'union',
									default: null,
									meta: [],
									settings: [],
									prop_types: {
										string: {
											kind: 'string',
											key: 'string',
											default: null,
											meta: {},
											settings: {
												enum: [
													'center center',
													'center left',
													'center right',
													'top center',
													'top left',
													'top right',
													'bottom center',
													'bottom left',
													'bottom right',
												],
											},
											dependencies: null,
											initial_value: null,
										},
										'background-image-position-offset': {
											kind: 'object',
											key: 'background-image-position-offset',
											default: null,
											meta: {},
											settings: {},
											shape: {
												x: {
													kind: 'union',
													default: null,
													meta: [],
													settings: [],
													prop_types: {
														size: {
															kind: 'object',
															key: 'size',
															default: null,
															meta: {},
															settings: {
																available_units: [
																	'px',
																	'em',
																	'rem',
																	'vw',
																	'vh',
																	'ch',
																	'%',
																],
															},
															shape: {
																unit: {
																	kind: 'string',
																	key: 'string',
																	default: null,
																	meta: {},
																	settings: {
																		enum: [
																			'px',
																			'em',
																			'rem',
																			'vw',
																			'vh',
																			'ch',
																			'%',
																			'auto',
																			'deg',
																			'rad',
																			'grad',
																			'turn',
																			's',
																			'ms',
																			'auto',
																			'custom',
																			'vmin',
																			'vmax',
																		],
																		required: true,
																	},
																	dependencies: null,
																	initial_value: null,
																},
																size: {
																	kind: 'union',
																	default: null,
																	meta: [],
																	settings: [],
																	prop_types: {
																		string: {
																			kind: 'string',
																			key: 'string',
																			default: null,
																			meta: {},
																			settings: {},
																			dependencies: null,
																			initial_value: null,
																		},
																		number: {
																			kind: 'number',
																			key: 'number',
																			default: null,
																			meta: {},
																			settings: {},
																			dependencies: null,
																			initial_value: null,
																		},
																		dynamic: {
																			kind: 'plain',
																			key: 'dynamic',
																			default: null,
																			meta: {},
																			settings: {
																				categories: [ 'text', 'number' ],
																			},
																			dependencies: null,
																			initial_value: null,
																		},
																	},
																	dependencies: null,
																	initial_value: null,
																},
															},
															dependencies: null,
															initial_value: null,
														},
														'global-size-variable': {
															kind: 'string',
															key: 'global-size-variable',
															default: null,
															meta: {},
															settings: {},
															dependencies: null,
															initial_value: null,
														},
													},
													dependencies: null,
													initial_value: null,
												},
												y: {
													kind: 'union',
													default: null,
													meta: [],
													settings: [],
													prop_types: {
														size: {
															kind: 'object',
															key: 'size',
															default: null,
															meta: {},
															settings: {
																available_units: [
																	'px',
																	'em',
																	'rem',
																	'vw',
																	'vh',
																	'ch',
																	'%',
																],
															},
															shape: {
																unit: {
																	kind: 'string',
																	key: 'string',
																	default: null,
																	meta: {},
																	settings: {
																		enum: [
																			'px',
																			'em',
																			'rem',
																			'vw',
																			'vh',
																			'ch',
																			'%',
																			'auto',
																			'deg',
																			'rad',
																			'grad',
																			'turn',
																			's',
																			'ms',
																			'auto',
																			'custom',
																			'vmin',
																			'vmax',
																		],
																		required: true,
																	},
																	dependencies: null,
																	initial_value: null,
																},
																size: {
																	kind: 'union',
																	default: null,
																	meta: [],
																	settings: [],
																	prop_types: {
																		string: {
																			kind: 'string',
																			key: 'string',
																			default: null,
																			meta: {},
																			settings: {},
																			dependencies: null,
																			initial_value: null,
																		},
																		number: {
																			kind: 'number',
																			key: 'number',
																			default: null,
																			meta: {},
																			settings: {},
																			dependencies: null,
																			initial_value: null,
																		},
																		dynamic: {
																			kind: 'plain',
																			key: 'dynamic',
																			default: null,
																			meta: {},
																			settings: {
																				categories: [ 'text', 'number' ],
																			},
																			dependencies: null,
																			initial_value: null,
																		},
																	},
																	dependencies: null,
																	initial_value: null,
																},
															},
															dependencies: null,
															initial_value: null,
														},
														'global-size-variable': {
															kind: 'string',
															key: 'global-size-variable',
															default: null,
															meta: {},
															settings: {},
															dependencies: null,
															initial_value: null,
														},
													},
													dependencies: null,
													initial_value: null,
												},
											},
											dependencies: null,
											initial_value: null,
										},
									},
									dependencies: null,
									initial_value: null,
								},
								attachment: {
									kind: 'string',
									key: 'string',
									default: null,
									meta: {},
									settings: {
										enum: [ 'fixed', 'scroll' ],
									},
									dependencies: null,
									initial_value: null,
								},
							},
							dependencies: null,
							initial_value: null,
						},
						'background-gradient-overlay': {
							kind: 'object',
							key: 'background-gradient-overlay',
							default: null,
							meta: {},
							settings: {},
							shape: {
								type: {
									kind: 'string',
									key: 'string',
									default: null,
									meta: {},
									settings: {
										enum: [ 'linear', 'radial' ],
									},
									dependencies: null,
									initial_value: null,
								},
								angle: {
									kind: 'number',
									key: 'number',
									default: null,
									meta: {},
									settings: {},
									dependencies: null,
									initial_value: null,
								},
								stops: {
									kind: 'array',
									key: 'gradient-color-stop',
									default: null,
									meta: {},
									settings: {},
									item_prop_type: {
										kind: 'object',
										key: 'color-stop',
										default: null,
										meta: {},
										settings: {},
										shape: {
											color: {
												kind: 'union',
												default: null,
												meta: [],
												settings: [],
												prop_types: {
													color: {
														kind: 'string',
														key: 'color',
														default: null,
														meta: {},
														settings: {},
														dependencies: null,
														initial_value: null,
													},
													'global-color-variable': {
														kind: 'string',
														key: 'global-color-variable',
														default: null,
														meta: {},
														settings: {},
														dependencies: null,
														initial_value: null,
													},
												},
												dependencies: null,
												initial_value: null,
											},
											offset: {
												kind: 'number',
												key: 'number',
												default: null,
												meta: {},
												settings: {},
												dependencies: null,
												initial_value: null,
											},
										},
										dependencies: null,
										initial_value: null,
									},
									dependencies: null,
									initial_value: null,
								},
								positions: {
									kind: 'string',
									key: 'string',
									default: null,
									meta: {},
									settings: {
										enum: [
											'center center',
											'center left',
											'center right',
											'top center',
											'top left',
											'top right',
											'bottom center',
											'bottom left',
											'bottom right',
										],
									},
									dependencies: null,
									initial_value: null,
								},
							},
							dependencies: null,
							initial_value: null,
						},
					},
					dependencies: null,
					initial_value: null,
				},
				dependencies: null,
				initial_value: null,
			},
			color: {
				kind: 'union',
				default: null,
				meta: [],
				settings: [],
				prop_types: {
					color: {
						kind: 'string',
						key: 'color',
						default: null,
						meta: {},
						settings: {},
						dependencies: null,
						initial_value: null,
					},
					'global-color-variable': {
						kind: 'string',
						key: 'global-color-variable',
						default: null,
						meta: {},
						settings: {},
						dependencies: null,
						initial_value: null,
					},
				},
				dependencies: null,
				initial_value: null,
			},
			clip: {
				kind: 'string',
				key: 'string',
				default: null,
				meta: {},
				settings: {
					enum: [ 'border-box', 'padding-box', 'content-box', 'text' ],
				},
				dependencies: null,
				initial_value: null,
			},
		},
		dependencies: null,
		initial_value: null,
	} as unknown as ObjectPropType,
	dynamicString: {
		kind: 'union',
		default: null,
		meta: {
			description: 'Test',
		},
		settings: {
			required: false,
		},
		prop_types: {
			string: _STRING_PROP_TYPE,
			dynamic: {
				kind: 'plain',
				key: 'dynamic',
				default: null,
				meta: {},
				settings: {
					categories: [ 'text', 'url', 'post_meta' ],
				},
			},
		},
	} as UnionPropType,
} as PropsSchema;

export const TAGS = {
	tags: {
		popup: {
			name: 'popup',
			categories: [ 'url' ],
			label: 'Popup',
			group: 'action',
			meta: [],
		},
		'off-canvas': {
			name: 'off-canvas',
			categories: [ 'url' ],
			label: 'Off-Canvas',
			group: 'action',
			meta: [],
		},
		'archive-description': {
			name: 'archive-description',
			categories: [ 'text' ],
			label: 'Archive Description',
			group: 'archive',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'archive-meta': {
			name: 'archive-meta',
			categories: [ 'text' ],
			label: 'Archive Meta',
			group: 'archive',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'archive-title': {
			name: 'archive-title',
			categories: [ 'text' ],
			label: 'Archive Title',
			group: 'archive',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'archive-url': {
			name: 'archive-url',
			categories: [ 'url' ],
			label: 'Archive URL',
			group: 'archive',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'author-info': {
			name: 'author-info',
			categories: [ 'text' ],
			label: 'Author Info',
			group: 'author',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'author-meta': {
			name: 'author-meta',
			categories: [ 'text' ],
			label: 'Author Meta',
			group: 'author',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'author-name': {
			name: 'author-name',
			categories: [ 'text' ],
			label: 'Author Name',
			group: 'author',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'author-profile-picture': {
			name: 'author-profile-picture',
			categories: [ 'image', 'media' ],
			label: 'Author Profile Picture',
			group: 'author',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'author-url': {
			name: 'author-url',
			categories: [ 'url' ],
			label: 'Author URL',
			group: 'author',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'comments-number': {
			name: 'comments-number',
			categories: [ 'text', 'number' ],
			label: 'Comments Number',
			group: 'comments',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'comments-url': {
			name: 'comments-url',
			categories: [ 'url' ],
			label: 'Comments URL',
			group: 'comments',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'page-title': {
			name: 'page-title',
			categories: [ 'text' ],
			label: 'Page Title',
			group: 'site',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'post-date': {
			name: 'post-date',
			categories: [ 'text' ],
			label: 'Post Date',
			group: 'post',
			atomic_controls: [ { type: 'control', value: { bind: 'fallback', type: 'text' } } ],
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'post-excerpt': {
			name: 'post-excerpt',
			categories: [ 'text' ],
			label: 'Post Excerpt',
			group: 'post',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'post-featured-image': {
			name: 'post-featured-image',
			categories: [ 'image', 'media' ],
			label: 'Featured Image',
			group: 'post',
			atomic_controls: [ { type: 'control', value: { bind: 'fallback', type: 'image' } } ],
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'post-gallery': {
			name: 'post-gallery',
			categories: [ 'gallery' ],
			label: 'Post Image Attachments',
			group: 'post',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'post-id': {
			name: 'post-id',
			categories: [ 'text', 'number' ],
			label: 'Post ID',
			group: 'post',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'post-time': {
			name: 'post-time',
			categories: [ 'text' ],
			label: 'Post Time',
			group: 'post',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'post-title': {
			name: 'post-title',
			categories: [ 'text' ],
			label: 'Post Title',
			group: 'post',
			atomic_controls: [ { type: 'control', value: { bind: 'fallback', type: 'text' } } ],
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'post-url': {
			name: 'post-url',
			categories: [ 'url' ],
			label: 'Post URL',
			group: 'post',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'site-logo': {
			name: 'site-logo',
			categories: [ 'image' ],
			label: 'Site Logo',
			group: 'site',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'site-tagline': {
			name: 'site-tagline',
			categories: [ 'text' ],
			label: 'Site Tagline',
			group: 'site',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'site-title': {
			name: 'site-title',
			categories: [ 'text' ],
			label: 'Site Title',
			group: 'site',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'site-url': {
			name: 'site-url',
			categories: [ 'url' ],
			label: 'Site URL',
			group: 'site',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'internal-url': {
			name: 'internal-url',
			categories: [ 'url' ],
			label: 'Internal URL',
			group: 'site',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'current-date-time': {
			name: 'current-date-time',
			categories: [ 'text' ],
			label: 'Current Date Time',
			group: 'site',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'reload-page': {
			name: 'reload-page',
			categories: [ 'url' ],
			label: 'Reload Page',
			group: 'action',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'request-arg': {
			name: 'request-arg',
			categories: [ 'text', 'post_meta' ],
			label: 'Request Parameter',
			group: 'site',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		lightbox: {
			name: 'lightbox',
			categories: [ 'url' ],
			label: 'Lightbox',
			group: 'action',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'featured-image-data': {
			name: 'featured-image-data',
			categories: [ 'text', 'url', 'post_meta' ],
			label: 'Featured Image Data',
			group: 'media',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		shortcode: {
			name: 'shortcode',
			categories: [ 'text', 'number', 'url', 'post_meta', 'datetime' ],
			label: 'Shortcode',
			group: 'site',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'contact-url': {
			name: 'contact-url',
			categories: [ 'url' ],
			label: 'Contact URL',
			group: 'site',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'user-info': {
			name: 'user-info',
			categories: [ 'text' ],
			label: 'User Info',
			group: 'site',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'user-profile-picture': {
			name: 'user-profile-picture',
			categories: [ 'image', 'media' ],
			label: 'User Profile Picture',
			group: 'author',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags',
			},
		},
		'post-custom-field': {
			name: 'post-custom-field',
			categories: [ 'text', 'url', 'post_meta', 'color', 'datetime', 'media', 'svg' ],
			label: 'Post Custom Field',
			group: 'post',
			meta: {
				origin: 'elementor',
				required_license: 'dynamic-tags-acf',
			},
		},
	},
	groups: {
		base: {
			title: 'Base Tags',
		},
		post: {
			title: 'Post',
		},
		archive: {
			title: 'Archive',
		},
		site: {
			title: 'Site',
		},
		media: {
			title: 'Media',
		},
		action: {
			title: 'Actions',
		},
		author: {
			title: 'Author',
		},
		comments: {
			title: 'Comments',
		},
		woocommerce: {
			title: 'WooCommerce',
		},
	},
};
