import { type ObjectPropType, type PropsSchema } from '../../types';

export const STUBS = {
	tag: {
		kind: 'string',
		key: 'string',
		settings: {},
		default: null,
		meta: {},
		dependencies: undefined,
		initial_value: null,
	},
	color: {
		kind: 'union',
		default: null,
		meta: {
			description: 'A color value prop type',
		},
		settings: {
			required: true,
		},
		prop_types: {
			color: {
				kind: 'string',
				key: 'color',
				default: null,
				meta: {},
				settings: {
					required: true,
				},
				dependencies: undefined,
				initial_value: {
					$$type: 'color',
					value: 'rgba(0, 0, 0, 1)',
				},
			},
			'global-color-variable': {
				kind: 'string',
				key: 'global-color-variable',
				default: null,
				meta: {},
				settings: {},
				dependencies: undefined,
				initial_value: null,
			},
		},
		dependencies: undefined,
		initial_value: {
			$$type: 'color',
			value: 'rgba(0, 0, 0, 1)',
		},
	},
	alignContent: {
		kind: 'string',
		key: 'string',
		default: null,
		meta: {
			description:
				"Aligns a flex container's lines within when there is extra space in the cross-axis. CSS values: center, start, end, space-between, space-around, space-evenly",
		},
		settings: {
			enum: [ 'center', 'start', 'end', 'space-between', 'space-around', 'space-evenly' ],
		},
		dependencies: undefined,
		initial_value: null,
	},
	background: {
		kind: 'object',
		key: 'background',
		default: null,
		meta: {},
		settings: {},
		shape: {
			'background-overlay': {
				kind: 'array',
				key: 'background-overlay',
				default: null,
				meta: {},
				settings: {},
				item_prop_type: {
					kind: 'union',
					default: null,
					meta: [],
					settings: [],
					prop_types: {
						'background-color-overlay': {
							kind: 'object',
							key: 'background-color-overlay',
							default: null,
							meta: {},
							settings: {},
							shape: {
								color: {
									kind: 'union',
									default: null,
									meta: [],
									settings: [],
									prop_types: {
										color: {
											kind: 'string',
											key: 'color',
											default: null,
											meta: {},
											settings: {},
											dependencies: null,
											initial_value: {
												$$type: 'color',
												value: '#00000033',
											},
										},
										'global-color-variable': {
											kind: 'string',
											key: 'global-color-variable',
											default: null,
											meta: {},
											settings: {},
											dependencies: null,
											initial_value: null,
										},
									},
									dependencies: null,
									initial_value: null,
								},
							},
							dependencies: null,
							initial_value: null,
						},
						'background-image-overlay': {
							kind: 'object',
							key: 'background-image-overlay',
							default: null,
							meta: {},
							settings: {},
							shape: {
								image: {
									kind: 'object',
									key: 'image',
									default: null,
									meta: {},
									settings: {},
									shape: {
										src: {
											kind: 'union',
											default: null,
											meta: [],
											settings: [],
											prop_types: {
												'image-src': {
													kind: 'object',
													key: 'image-src',
													default: null,
													meta: {},
													settings: {
														required: true,
													},
													shape: {
														id: {
															kind: 'union',
															default: null,
															meta: [],
															settings: [],
															prop_types: {
																'image-attachment-id': {
																	kind: 'number',
																	key: 'image-attachment-id',
																	default: null,
																	meta: {
																		description:
																			'The ID of the image attachment in the WordPress media library, applicable for internal images only',
																	},
																	settings: {},
																	dependencies: null,
																	initial_value: null,
																},
																dynamic: {
																	kind: 'plain',
																	key: 'dynamic',
																	default: null,
																	meta: {},
																	settings: {
																		categories: [ 'number' ],
																	},
																	dependencies: null,
																	initial_value: null,
																},
															},
															dependencies: null,
															initial_value: null,
														},
														url: {
															kind: 'union',
															default: null,
															meta: [],
															settings: [],
															prop_types: {
																url: {
																	kind: 'string',
																	key: 'url',
																	default: null,
																	meta: {},
																	settings: {},
																	dependencies: null,
																	initial_value: null,
																},
																dynamic: {
																	kind: 'plain',
																	key: 'dynamic',
																	default: null,
																	meta: {},
																	settings: {
																		categories: [ 'url' ],
																	},
																	dependencies: null,
																	initial_value: null,
																},
															},
															dependencies: null,
															initial_value: null,
														},
													},
													dependencies: null,
													initial_value: null,
												},
												dynamic: {
													kind: 'plain',
													key: 'dynamic',
													default: null,
													meta: {},
													settings: {
														categories: [ 'image' ],
													},
													dependencies: null,
													initial_value: null,
												},
											},
											dependencies: null,
											initial_value: null,
										},
										size: {
											kind: 'string',
											key: 'string',
											default: null,
											meta: {
												description:
													"The image file size to use, affecting quality only!. This DOES NOT affect dimensions on the page. For affecting dimensions, use the element's style schema instead",
											},
											settings: {
												enum: [
													'thumbnail',
													'medium',
													'medium_large',
													'large',
													'1536x1536',
													'2048x2048',
													'full',
												],
												required: true,
											},
											dependencies: null,
											initial_value: {
												$$type: 'string',
												value: 'large',
											},
										},
									},
									dependencies: null,
									initial_value: null,
								},
								repeat: {
									kind: 'string',
									key: 'string',
									default: null,
									meta: {},
									settings: {
										enum: [ 'repeat', 'repeat-x', 'repeat-y', 'no-repeat' ],
									},
									dependencies: null,
									initial_value: null,
								},
								size: {
									kind: 'union',
									default: null,
									meta: [],
									settings: [],
									prop_types: {
										string: {
											kind: 'string',
											key: 'string',
											default: null,
											meta: {},
											settings: {
												enum: [ 'auto', 'cover', 'contain' ],
											},
											dependencies: null,
											initial_value: null,
										},
										'background-image-size-scale': {
											kind: 'object',
											key: 'background-image-size-scale',
											default: null,
											meta: {},
											settings: {},
											shape: {
												width: {
													kind: 'union',
													default: null,
													meta: [],
													settings: [],
													prop_types: {
														size: {
															kind: 'object',
															key: 'size',
															default: null,
															meta: {},
															settings: {
																available_units: [
																	'px',
																	'em',
																	'rem',
																	'vw',
																	'vh',
																	'ch',
																	'%',
																	'auto',
																],
															},
															shape: {
																unit: {
																	kind: 'string',
																	key: 'string',
																	default: null,
																	meta: {},
																	settings: {
																		enum: [
																			'px',
																			'em',
																			'rem',
																			'vw',
																			'vh',
																			'ch',
																			'%',
																			'auto',
																			'deg',
																			'rad',
																			'grad',
																			'turn',
																			's',
																			'ms',
																			'auto',
																			'custom',
																			'vmin',
																			'vmax',
																		],
																		required: true,
																	},
																	dependencies: null,
																	initial_value: null,
																},
																size: {
																	kind: 'union',
																	default: null,
																	meta: [],
																	settings: [],
																	prop_types: {
																		string: {
																			kind: 'string',
																			key: 'string',
																			default: null,
																			meta: {},
																			settings: {},
																			dependencies: null,
																			initial_value: null,
																		},
																		number: {
																			kind: 'number',
																			key: 'number',
																			default: null,
																			meta: {},
																			settings: {},
																			dependencies: null,
																			initial_value: null,
																		},
																		dynamic: {
																			kind: 'plain',
																			key: 'dynamic',
																			default: null,
																			meta: {},
																			settings: {
																				categories: [ 'text', 'number' ],
																			},
																			dependencies: null,
																			initial_value: null,
																		},
																	},
																	dependencies: null,
																	initial_value: null,
																},
															},
															dependencies: null,
															initial_value: null,
														},
														'global-size-variable': {
															kind: 'string',
															key: 'global-size-variable',
															default: null,
															meta: {},
															settings: {},
															dependencies: null,
															initial_value: null,
														},
													},
													dependencies: null,
													initial_value: null,
												},
												height: {
													kind: 'union',
													default: null,
													meta: [],
													settings: [],
													prop_types: {
														size: {
															kind: 'object',
															key: 'size',
															default: null,
															meta: {},
															settings: {
																available_units: [
																	'px',
																	'em',
																	'rem',
																	'vw',
																	'vh',
																	'ch',
																	'%',
																	'auto',
																],
															},
															shape: {
																unit: {
																	kind: 'string',
																	key: 'string',
																	default: null,
																	meta: {},
																	settings: {
																		enum: [
																			'px',
																			'em',
																			'rem',
																			'vw',
																			'vh',
																			'ch',
																			'%',
																			'auto',
																			'deg',
																			'rad',
																			'grad',
																			'turn',
																			's',
																			'ms',
																			'auto',
																			'custom',
																			'vmin',
																			'vmax',
																		],
																		required: true,
																	},
																	dependencies: null,
																	initial_value: null,
																},
																size: {
																	kind: 'union',
																	default: null,
																	meta: [],
																	settings: [],
																	prop_types: {
																		string: {
																			kind: 'string',
																			key: 'string',
																			default: null,
																			meta: {},
																			settings: {},
																			dependencies: null,
																			initial_value: null,
																		},
																		number: {
																			kind: 'number',
																			key: 'number',
																			default: null,
																			meta: {},
																			settings: {},
																			dependencies: null,
																			initial_value: null,
																		},
																		dynamic: {
																			kind: 'plain',
																			key: 'dynamic',
																			default: null,
																			meta: {},
																			settings: {
																				categories: [ 'text', 'number' ],
																			},
																			dependencies: null,
																			initial_value: null,
																		},
																	},
																	dependencies: null,
																	initial_value: null,
																},
															},
															dependencies: null,
															initial_value: null,
														},
														'global-size-variable': {
															kind: 'string',
															key: 'global-size-variable',
															default: null,
															meta: {},
															settings: {},
															dependencies: null,
															initial_value: null,
														},
													},
													dependencies: null,
													initial_value: null,
												},
											},
											dependencies: null,
											initial_value: null,
										},
									},
									dependencies: null,
									initial_value: null,
								},
								position: {
									kind: 'union',
									default: null,
									meta: [],
									settings: [],
									prop_types: {
										string: {
											kind: 'string',
											key: 'string',
											default: null,
											meta: {},
											settings: {
												enum: [
													'center center',
													'center left',
													'center right',
													'top center',
													'top left',
													'top right',
													'bottom center',
													'bottom left',
													'bottom right',
												],
											},
											dependencies: null,
											initial_value: null,
										},
										'background-image-position-offset': {
											kind: 'object',
											key: 'background-image-position-offset',
											default: null,
											meta: {},
											settings: {},
											shape: {
												x: {
													kind: 'union',
													default: null,
													meta: [],
													settings: [],
													prop_types: {
														size: {
															kind: 'object',
															key: 'size',
															default: null,
															meta: {},
															settings: {
																available_units: [
																	'px',
																	'em',
																	'rem',
																	'vw',
																	'vh',
																	'ch',
																	'%',
																],
															},
															shape: {
																unit: {
																	kind: 'string',
																	key: 'string',
																	default: null,
																	meta: {},
																	settings: {
																		enum: [
																			'px',
																			'em',
																			'rem',
																			'vw',
																			'vh',
																			'ch',
																			'%',
																			'auto',
																			'deg',
																			'rad',
																			'grad',
																			'turn',
																			's',
																			'ms',
																			'auto',
																			'custom',
																			'vmin',
																			'vmax',
																		],
																		required: true,
																	},
																	dependencies: null,
																	initial_value: null,
																},
																size: {
																	kind: 'union',
																	default: null,
																	meta: [],
																	settings: [],
																	prop_types: {
																		string: {
																			kind: 'string',
																			key: 'string',
																			default: null,
																			meta: {},
																			settings: {},
																			dependencies: null,
																			initial_value: null,
																		},
																		number: {
																			kind: 'number',
																			key: 'number',
																			default: null,
																			meta: {},
																			settings: {},
																			dependencies: null,
																			initial_value: null,
																		},
																		dynamic: {
																			kind: 'plain',
																			key: 'dynamic',
																			default: null,
																			meta: {},
																			settings: {
																				categories: [ 'text', 'number' ],
																			},
																			dependencies: null,
																			initial_value: null,
																		},
																	},
																	dependencies: null,
																	initial_value: null,
																},
															},
															dependencies: null,
															initial_value: null,
														},
														'global-size-variable': {
															kind: 'string',
															key: 'global-size-variable',
															default: null,
															meta: {},
															settings: {},
															dependencies: null,
															initial_value: null,
														},
													},
													dependencies: null,
													initial_value: null,
												},
												y: {
													kind: 'union',
													default: null,
													meta: [],
													settings: [],
													prop_types: {
														size: {
															kind: 'object',
															key: 'size',
															default: null,
															meta: {},
															settings: {
																available_units: [
																	'px',
																	'em',
																	'rem',
																	'vw',
																	'vh',
																	'ch',
																	'%',
																],
															},
															shape: {
																unit: {
																	kind: 'string',
																	key: 'string',
																	default: null,
																	meta: {},
																	settings: {
																		enum: [
																			'px',
																			'em',
																			'rem',
																			'vw',
																			'vh',
																			'ch',
																			'%',
																			'auto',
																			'deg',
																			'rad',
																			'grad',
																			'turn',
																			's',
																			'ms',
																			'auto',
																			'custom',
																			'vmin',
																			'vmax',
																		],
																		required: true,
																	},
																	dependencies: null,
																	initial_value: null,
																},
																size: {
																	kind: 'union',
																	default: null,
																	meta: [],
																	settings: [],
																	prop_types: {
																		string: {
																			kind: 'string',
																			key: 'string',
																			default: null,
																			meta: {},
																			settings: {},
																			dependencies: null,
																			initial_value: null,
																		},
																		number: {
																			kind: 'number',
																			key: 'number',
																			default: null,
																			meta: {},
																			settings: {},
																			dependencies: null,
																			initial_value: null,
																		},
																		dynamic: {
																			kind: 'plain',
																			key: 'dynamic',
																			default: null,
																			meta: {},
																			settings: {
																				categories: [ 'text', 'number' ],
																			},
																			dependencies: null,
																			initial_value: null,
																		},
																	},
																	dependencies: null,
																	initial_value: null,
																},
															},
															dependencies: null,
															initial_value: null,
														},
														'global-size-variable': {
															kind: 'string',
															key: 'global-size-variable',
															default: null,
															meta: {},
															settings: {},
															dependencies: null,
															initial_value: null,
														},
													},
													dependencies: null,
													initial_value: null,
												},
											},
											dependencies: null,
											initial_value: null,
										},
									},
									dependencies: null,
									initial_value: null,
								},
								attachment: {
									kind: 'string',
									key: 'string',
									default: null,
									meta: {},
									settings: {
										enum: [ 'fixed', 'scroll' ],
									},
									dependencies: null,
									initial_value: null,
								},
							},
							dependencies: null,
							initial_value: null,
						},
						'background-gradient-overlay': {
							kind: 'object',
							key: 'background-gradient-overlay',
							default: null,
							meta: {},
							settings: {},
							shape: {
								type: {
									kind: 'string',
									key: 'string',
									default: null,
									meta: {},
									settings: {
										enum: [ 'linear', 'radial' ],
									},
									dependencies: null,
									initial_value: null,
								},
								angle: {
									kind: 'number',
									key: 'number',
									default: null,
									meta: {},
									settings: {},
									dependencies: null,
									initial_value: null,
								},
								stops: {
									kind: 'array',
									key: 'gradient-color-stop',
									default: null,
									meta: {},
									settings: {},
									item_prop_type: {
										kind: 'object',
										key: 'color-stop',
										default: null,
										meta: {},
										settings: {},
										shape: {
											color: {
												kind: 'union',
												default: null,
												meta: [],
												settings: [],
												prop_types: {
													color: {
														kind: 'string',
														key: 'color',
														default: null,
														meta: {},
														settings: {},
														dependencies: null,
														initial_value: null,
													},
													'global-color-variable': {
														kind: 'string',
														key: 'global-color-variable',
														default: null,
														meta: {},
														settings: {},
														dependencies: null,
														initial_value: null,
													},
												},
												dependencies: null,
												initial_value: null,
											},
											offset: {
												kind: 'number',
												key: 'number',
												default: null,
												meta: {},
												settings: {},
												dependencies: null,
												initial_value: null,
											},
										},
										dependencies: null,
										initial_value: null,
									},
									dependencies: null,
									initial_value: null,
								},
								positions: {
									kind: 'string',
									key: 'string',
									default: null,
									meta: {},
									settings: {
										enum: [
											'center center',
											'center left',
											'center right',
											'top center',
											'top left',
											'top right',
											'bottom center',
											'bottom left',
											'bottom right',
										],
									},
									dependencies: null,
									initial_value: null,
								},
							},
							dependencies: null,
							initial_value: null,
						},
					},
					dependencies: null,
					initial_value: null,
				},
				dependencies: null,
				initial_value: null,
			},
			color: {
				kind: 'union',
				default: null,
				meta: [],
				settings: [],
				prop_types: {
					color: {
						kind: 'string',
						key: 'color',
						default: null,
						meta: {},
						settings: {},
						dependencies: null,
						initial_value: null,
					},
					'global-color-variable': {
						kind: 'string',
						key: 'global-color-variable',
						default: null,
						meta: {},
						settings: {},
						dependencies: null,
						initial_value: null,
					},
				},
				dependencies: null,
				initial_value: null,
			},
			clip: {
				kind: 'string',
				key: 'string',
				default: null,
				meta: {},
				settings: {
					enum: [ 'border-box', 'padding-box', 'content-box', 'text' ],
				},
				dependencies: null,
				initial_value: null,
			},
		},
		dependencies: null,
		initial_value: null,
	} as unknown as ObjectPropType,
} as PropsSchema;
