<?php

namespace Elementor\Modules\AtomicWidgets\Elements\Atomic_Carousel;

use Elementor\Modules\AtomicWidgets\ChildrenDependencies\Child_Dependency;
use Elementor\Modules\AtomicWidgets\Controls\Section;
use Elementor\Modules\AtomicWidgets\Controls\Types\Number_Control;
use Elementor\Modules\AtomicWidgets\Controls\Types\Select_Control;
use Elementor\Modules\AtomicWidgets\Controls\Types\Switch_Control;
use Elementor\Modules\AtomicWidgets\Controls\Types\Text_Control;
use Elementor\Modules\AtomicWidgets\DynamicTags\Dynamic_Prop_Type;
use Elementor\Modules\AtomicWidgets\Elements\Atomic_Carousel\Atomic_Carousel_Arrow_Next\Atomic_Carousel_Arrow_Next;
use Elementor\Modules\AtomicWidgets\Elements\Atomic_Carousel\Atomic_Carousel_Arrow_Prev\Atomic_Carousel_Arrow_Prev;
use Elementor\Modules\AtomicWidgets\Elements\Atomic_Carousel\Atomic_Carousel_Container\Atomic_Carousel_Container;
use Elementor\Modules\AtomicWidgets\Elements\Atomic_Carousel\Atomic_Carousel_Pagination\Atomic_Carousel_Pagination;
use Elementor\Modules\AtomicWidgets\Elements\Atomic_Carousel\Atomic_Carousel_Slide\Atomic_Carousel_Slide;
use Elementor\Modules\AtomicWidgets\Elements\Atomic_Carousel\Atomic_Carousel_Viewport\Atomic_Carousel_Viewport;
use Elementor\Modules\AtomicWidgets\Elements\Base\Atomic_Element_Base;
use Elementor\Modules\AtomicWidgets\Elements\Base\Element_Builder;
use Elementor\Modules\AtomicWidgets\Elements\Base\Has_Element_Template;
use Elementor\Modules\AtomicWidgets\Elements\Loader\Frontend_Assets_Loader;
use Elementor\Modules\AtomicWidgets\PropDependencies\Manager as Dependency_Manager;
use Elementor\Modules\AtomicWidgets\PropTypes\Attributes_Prop_Type;
use Elementor\Modules\AtomicWidgets\PropTypes\Classes_Prop_Type;
use Elementor\Modules\AtomicWidgets\PropTypes\Primitives\Boolean_Prop_Type;
use Elementor\Modules\AtomicWidgets\PropTypes\Primitives\Number_Prop_Type;
use Elementor\Modules\AtomicWidgets\PropTypes\Primitives\String_Prop_Type;
use Elementor\Modules\AtomicWidgets\Styles\Style_Definition;
use Elementor\Modules\AtomicWidgets\Styles\Style_Variant;
use Elementor\Modules\AtomicWidgets\Utils\Element_Position;
use Elementor\Modules\Components\PropTypes\Overridable_Prop_Type;
use Elementor\Plugin;
use Elementor\Utils;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

/**
 * V4 Carousel root element (ED-25236 / ED-25237).
 *
 * Engine is Embla Carousel, bundled into `carousel-handler.js`. Embla is headless: it owns
 * scroll physics and snap points only, while every visible node below is a real V4 element the
 * user can style and fill.
 *
 * Three deliberate deviations from the spec, each recorded in
 * docs/carousel_v4_library_research.md with the measurement that motivated it:
 *  - `transition_speed` is stored in milliseconds and mapped to Embla's `duration` in the
 *    handler, so the saved value never carries an engine-specific physics constant.
 *  - The autoplay pause/play button is generated by the handler rather than being an eighth
 *    persisted sub-element, because the saved child tree cannot be migrated today.
 *  - Arrow base styles use logical inset properties so they follow `dir` in RTL.
 */
class Atomic_Carousel extends Atomic_Element_Base {
	use Has_Element_Template;

	const BASE_STYLE_KEY = 'base';

	const ELEMENT_TYPE_VIEWPORT = 'e-carousel-viewport';
	const ELEMENT_TYPE_CONTAINER = 'e-carousel-container';
	const ELEMENT_TYPE_SLIDE = 'e-carousel-slide';
	const ELEMENT_TYPE_ARROW_PREV = 'e-carousel-arrow-prev';
	const ELEMENT_TYPE_ARROW_NEXT = 'e-carousel-arrow-next';
	const ELEMENT_TYPE_PAGINATION = 'e-carousel-pagination';

	const DEFAULT_SLIDE_COUNT = 4;

	public static $widget_description = 'A carousel of slides with arrow navigation and dot pagination. REQUIRED child: e-carousel-viewport, which contains a single e-carousel-container holding the e-carousel-slide elements. Optional direct children: e-carousel-arrow-prev, e-carousel-arrow-next (each wraps any element as the arrow content) and e-carousel-pagination (dots are generated at runtime). Arrows and pagination are siblings of the viewport, never children of it, so dragging a slide never starts on an arrow.';

	public function __construct( $data = [], $args = null ) {
		parent::__construct( $data, $args );
		$this->meta( 'is_container', true );
	}

	public static function get_type() {
		return 'e-carousel';
	}

	public static function get_element_type(): string {
		return 'e-carousel';
	}

	public function get_title() {
		return esc_html__( 'Carousel', 'elementor' );
	}

	public function get_keywords() {
		return [ 'ato', 'atom', 'atoms', 'atomic', 'carousel', 'slider', 'slides' ];
	}

	public function get_icon() {
		return 'eicon-nested-carousel';
	}

	protected static function define_props_schema(): array {
		$when_autoplay_on = Dependency_Manager::make()
			->where( [
				'operator' => 'eq',
				'path' => [ 'autoplay' ],
				'value' => true,
			] )
			->get();

		// Fade stacks every slide on top of each other, so "how many are visible" and
		// "how many to advance" stop being meaningful. Hide both while fade is selected.
		$when_transition_is_slide = Dependency_Manager::make()
			->where( [
				'operator' => 'eq',
				'path' => [ 'transition_type' ],
				'value' => 'slide',
			] )
			->get();

		return [
			'classes' => Classes_Prop_Type::make()->default( [] ),
			'transition_type' => String_Prop_Type::make()
				->enum( [ 'slide', 'fade' ] )
				->default( 'slide' )
				->description( 'How the carousel moves between slides. `slide` scrolls horizontally, `fade` cross-fades and forces a single slide per view.' ),
			'slides_per_view' => Number_Prop_Type::make()
				->default( 3 )
				->set_dependencies( $when_transition_is_slide )
				->meta( Dynamic_Prop_Type::ignore() )
				->description( 'How many slides are visible at once, 1 to 10.' ),
			'slides_to_scroll' => Number_Prop_Type::make()
				->default( 1 )
				->set_dependencies( $when_transition_is_slide )
				->meta( Dynamic_Prop_Type::ignore() )
				->description( 'How many slides each arrow or dot click advances, 1 to 10.' ),
			'loop' => Boolean_Prop_Type::make()
				->default( false )
				->description( 'Scroll past the last slide back to the first. Implemented by repositioning slides, so no slide is ever duplicated.' ),
			'autoplay' => Boolean_Prop_Type::make()
				->default( false )
				->description( 'Advance slides automatically. Always off inside the editor.' ),
			'autoplay_delay' => Number_Prop_Type::make()
				->default( 5000 )
				->set_dependencies( $when_autoplay_on )
				->meta( Dynamic_Prop_Type::ignore() )
				->meta( 'suffix', 'MS' )
				->description( 'Milliseconds each slide stays on screen while autoplay runs.' ),
			'pause_on_hover' => Boolean_Prop_Type::make()
				->default( true )
				->set_dependencies( $when_autoplay_on )
				->description( 'Pause autoplay while the pointer is over the carousel.' ),
			'pause_on_interaction' => Boolean_Prop_Type::make()
				->default( true )
				->set_dependencies( $when_autoplay_on )
				->description( 'Pause autoplay once the visitor drags or clicks their way through the slides.' ),
			'show_autoplay_button' => Boolean_Prop_Type::make()
				->default( true )
				->set_dependencies( $when_autoplay_on )
				->description( 'Show a pause/play button. Required by WCAG 2.2.2 whenever content moves on its own.' ),
			// Milliseconds, not Embla's `duration`. Embla's unit is a spring constant where the
			// documented usable band is 20-60 and 100 produces a ~9 second transition, so the
			// handler converts. Keeping ms here also keeps the engine out of the saved data.
			'transition_speed' => Number_Prop_Type::make()
				->default( 600 )
				->meta( Dynamic_Prop_Type::ignore() )
				->meta( 'suffix', 'MS' )
				->description( 'How long one transition takes, in milliseconds.' ),
			'show_arrows' => Boolean_Prop_Type::make()
				->default( true )
				->description( 'Show the previous/next arrow elements. Turning this off removes them from the DOM and the Structure panel.' ),
			'show_pagination' => Boolean_Prop_Type::make()
				->default( true )
				->description( 'Show the pagination dots. Turning this off removes them from the DOM and the Structure panel.' ),
			'attributes' => Attributes_Prop_Type::make()->meta( Overridable_Prop_Type::ignore() ),
		];
	}

	protected function define_atomic_controls(): array {
		return [
			Section::make()
				->set_label( __( 'Content', 'elementor' ) )
				->set_id( 'content' )
				->set_items( [
					// A dedicated Slides repeater control (mirroring Tabs_Control) is a separate
					// task; until then slides are managed from the Structure panel.
					Switch_Control::bind_to( 'show_arrows' )
						->set_label( esc_html__( 'Show Arrows', 'elementor' ) ),
					Switch_Control::bind_to( 'show_pagination' )
						->set_label( esc_html__( 'Show Pagination', 'elementor' ) ),
				] ),
			Section::make()
				->set_label( __( 'Settings', 'elementor' ) )
				->set_id( 'settings' )
				->set_items( [
					Select_Control::bind_to( 'transition_type' )
						->set_label( esc_html__( 'Transition', 'elementor' ) )
						->set_options( [
							[
								'value' => 'slide',
								'label' => esc_html__( 'Slide', 'elementor' ),
							],
							[
								'value' => 'fade',
								'label' => esc_html__( 'Fade', 'elementor' ),
							],
						] ),
					Number_Control::bind_to( 'slides_per_view' )
						->set_label( esc_html__( 'Slides Per View', 'elementor' ) )
						->set_min( 1 )
						->set_max( 10 )
						->set_should_force_int( true ),
					Number_Control::bind_to( 'slides_to_scroll' )
						->set_label( esc_html__( 'Slides Per Scroll', 'elementor' ) )
						->set_min( 1 )
						->set_max( 10 )
						->set_should_force_int( true ),
					Switch_Control::bind_to( 'loop' )
						->set_label( esc_html__( 'Loop', 'elementor' ) ),
					Switch_Control::bind_to( 'autoplay' )
						->set_label( esc_html__( 'Autoplay', 'elementor' ) ),
					Number_Control::bind_to( 'autoplay_delay' )
						->set_label( esc_html__( 'Autoplay Delay', 'elementor' ) )
						->set_min( 100 )
						->set_max( 60000 )
						->set_step( 100 ),
					Switch_Control::bind_to( 'pause_on_hover' )
						->set_label( esc_html__( 'Pause on Hover', 'elementor' ) ),
					Switch_Control::bind_to( 'pause_on_interaction' )
						->set_label( esc_html__( 'Pause on Interaction', 'elementor' ) ),
					Switch_Control::bind_to( 'show_autoplay_button' )
						->set_label( esc_html__( 'Show Pause/Play Button', 'elementor' ) ),
					Number_Control::bind_to( 'transition_speed' )
						->set_label( esc_html__( 'Transition Speed', 'elementor' ) )
						->set_min( 100 )
						->set_max( 3000 )
						->set_step( 50 ),
					Text_Control::bind_to( '_cssid' )
						->set_label( __( 'ID', 'elementor' ) )
						->set_meta( $this->get_css_id_control_meta() ),
				] ),
		];
	}

	protected function define_base_styles(): array {
		return [
			static::BASE_STYLE_KEY => Style_Definition::make()
				->add_variant(
					Style_Variant::make()
						->add_props( [
							'position' => String_Prop_Type::generate( 'relative' ),
						] )
				),
		];
	}

	protected function define_default_children() {
		$slides = [];

		// Four slides at three per view means the fourth sits off-screen, so the arrows and dots
		// are live the moment the element is dropped instead of looking broken.
		foreach ( range( 1, self::DEFAULT_SLIDE_COUNT ) as $i ) {
			$slides[] = Atomic_Carousel_Slide::generate()
				->editor_settings( [
					/* translators: %d: Slide number. */
					'title' => sprintf( esc_html__( 'Slide %d', 'elementor' ), $i ),
					'initial_position' => $i,
				] )
				->build();
		}

		$viewport = Atomic_Carousel_Viewport::generate()
			->meta( [ 'required' => true ] )
			->editor_settings( [
				'title' => esc_html__( 'Viewport', 'elementor' ),
			] )
			->children( [
				Atomic_Carousel_Container::generate()
					->meta( [ 'required' => true ] )
					->editor_settings( [
						'title' => esc_html__( 'Slides', 'elementor' ),
					] )
					->children( $slides )
					->build(),
			] )
			->build();

		return [
			$viewport,
			Atomic_Carousel_Arrow_Prev::build_default_element(),
			Atomic_Carousel_Arrow_Next::build_default_element(),
			Atomic_Carousel_Pagination::build_default_element(),
		];
	}

	/**
	 * `show_arrows` and `show_pagination` attach and detach real child elements rather than
	 * hiding them with CSS, so a hidden arrow costs nothing in the DOM or the Structure panel.
	 *
	 * The stash is session storage only: detaching, saving and returning in a later session
	 * restores `default_model`, not the visitor's customised arrow content. That trade-off is
	 * inherited from e-background-video and is flagged as R2 in the research doc.
	 */
	protected function define_children_dependencies(): array {
		$shown = fn( string $prop ) => Dependency_Manager::make()->where( [
			'operator' => 'ne',
			'path' => [ $prop ],
			'value' => false,
		] );

		return [
			Child_Dependency::for( self::ELEMENT_TYPE_ARROW_PREV )
				->when( $shown( 'show_arrows' ) )
				->position( Element_Position::last() )
				->stash( true )
				->default_model(
					Element_Builder::make( self::ELEMENT_TYPE_ARROW_PREV )
						->is_locked( true )
						->hydrate_default_children( true )
						->build()
				),
			Child_Dependency::for( self::ELEMENT_TYPE_ARROW_NEXT )
				->when( $shown( 'show_arrows' ) )
				->position( Element_Position::last() )
				->stash( true )
				->default_model(
					Element_Builder::make( self::ELEMENT_TYPE_ARROW_NEXT )
						->is_locked( true )
						->hydrate_default_children( true )
						->build()
				),
			Child_Dependency::for( self::ELEMENT_TYPE_PAGINATION )
				->when( $shown( 'show_pagination' ) )
				->position( Element_Position::last() )
				->stash( true )
				->default_model(
					Element_Builder::make( self::ELEMENT_TYPE_PAGINATION )
						->is_locked( true )
						->build()
				),
		];
	}

	protected function define_allowed_child_types() {
		return [
			self::ELEMENT_TYPE_VIEWPORT,
			self::ELEMENT_TYPE_ARROW_PREV,
			self::ELEMENT_TYPE_ARROW_NEXT,
			self::ELEMENT_TYPE_PAGINATION,
		];
	}

	public function get_script_depends() {
		$global_depends = parent::get_script_depends();

		return array_merge( $global_depends, [ 'elementor-carousel-handler' ] );
	}

	public function register_frontend_handlers() {
		$assets_url = ELEMENTOR_ASSETS_URL;
		$min_suffix = ( Utils::is_script_debug() || Utils::is_elementor_tests() ) ? '' : '.min';

		wp_register_script(
			'elementor-carousel-handler',
			"{$assets_url}js/carousel-handler{$min_suffix}.js",
			[ Frontend_Assets_Loader::FRONTEND_HANDLERS_HANDLE ],
			ELEMENTOR_VERSION,
			true
		);
	}

	protected function build_template_context(): array {
		$settings = $this->get_atomic_settings();

		return array_merge( $this->build_base_template_context(), [
			'is_editor' => Plugin::$instance->preview->is_preview_mode(),
			'aria_label' => esc_attr__( 'Carousel', 'elementor' ),
			'slides_per_view' => 'fade' === ( $settings['transition_type'] ?? 'slide' )
				? 1
				: (int) ( $settings['slides_per_view'] ?? 3 ),
		] );
	}

	protected function get_templates(): array {
		return [
			'elementor/elements/atomic-carousel' => __DIR__ . '/atomic-carousel.html.twig',
		];
	}
}
