<?php
namespace Elementor\Modules\Presets\Data;

use \Elementor\Data\Base\Controller as Base_Controller;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

class Controller extends Base_Controller {
	/**
	 * @return string
	 */
	public function get_name() {
		return 'presets';
	}

	public function register_internal_endpoints() {
		// Register as internal to remove the default endpoint generated by the base controller.
		$this->register_endpoint( Endpoints\Index::class );
	}

	public function register_endpoints() {

	}

}
