name: Get Next Release Branch
description: Get the next release branch version channel & number and increment it. Sets the version as ENV variable.

inputs:
  INPUT_VERSION:
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
            if [ "${{ inputs.INPUT_VERSION }}" == "" ];
              then
                PACKAGE_VERSION=$(node -p "require('./package.json').version")
                npm install --no-package-lock --no-save semver@7.3.4
                NEXT_PACKAGE_VERSION=$(npx semver $PACKAGE_VERSION -i minor)
                RELEASE_BRANCH="release/${NEXT_PACKAGE_VERSION}"
              else
                echo "Version var is set to ${{ inputs.INPUT_VERSION }}"
                RELEASE_BRANCH="release/${{ inputs.INPUT_VERSION }}"
              fi
              echo "RELEASE_BRANCH=${RELEASE_BRANCH}" >> $GITHUB_ENV
              echo "RELEASE_BRANCH : ${RELEASE_BRANCH}"
      
