export {
	slice,
	registerOnboardingSlice,
	initFromConfig,
	goToStep,
	goToStepIndex,
	nextStep,
	prevStep,
	completeStep,
	setUserChoice,
	setUserChoices,
	setExitType,
	startOnboarding,
	completeOnboarding,
	setLoading,
	setError,
	clearUnexpectedExit,
	setConnected,
	setGuest,
} from './slice';

export {
	selectOnboarding,
	selectSteps,
	selectCurrentStepId,
	selectCurrentStepIndex,
	selectCompletedSteps,
	selectChoices,
	selectIsLoading,
	selectError,
	selectHadUnexpectedExit,
	selectIsConnected,
	selectIsGuest,
	selectUserName,
	selectUrls,
	selectCurrentStep,
	selectIsFirstStep,
	selectIsLastStep,
	selectTotalSteps,
	selectIsStepCompleted,
	selectHasPassedLogin,
} from './selectors';
