<?php

namespace Elementor;

abstract class Widget_Base_V2 extends Widget_Base {
	abstract public function get_v2_controls();

	public function get_initial_config()
	{
		$config =  parent::get_initial_config(); // TODO: Change the autogenerated stub

		$config[ 'controls' ] = $this->get_v2_controls();

		return $config;
	}

	public function get_stack($with_common_controls = true) {
		return [
			'controls' => [],
			'tabs' => [],
		];
	}
}
