<?php

namespace Elementor;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

class Widget_Heading_V2 extends Widget_Base_V2 {
	public function get_v2_controls() {
		return [
			'blabla' => 'blabla',
		];
	}

	public function get_icon() {
		return 'eicon-t-letter';
	}

	public function get_title() {
		return 'Heading V2';
	}

	public function get_name() {
		return 'heading-v2';
	}

	public function get_initial_config()
	{
		$config =  parent::get_initial_config(); // TODO: Change the autogenerated stub

		$config[ 'controls' ] = $this->get_v2_controls();

		return $config;
	}

	protected function render() {
		echo '<h2>' . 'Heading ' . '</h2>';
	}
}

