import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolveFromRoot } from '../vite/shared/paths.mjs';

const FRONTEND_AVAILABLE_ICONS = [
	'chevron-left',
	'chevron-right',
	'close',
	'download-bold',
	'facebook',
	'frame-expand',
	'frame-minimize',
	'loading',
	'pinterest',
	'share-arrow',
	'twitter',
	'x-twitter',
	'zoom-in-bold',
	'zoom-out-bold',
];

function dashCaseToCamelCase( string ) {
	return string.replace( /\b-([a-z])/g, ( _, char ) => char.toUpperCase() );
}

function getIconsManagerInstanceContent() {
	return `import IconsManager from './manager';

const iconsManager = new IconsManager( 'eicon' );`;
}

function getIconJSContent( iconName, svgData ) {
	const { path, width, height } = svgData;
	const svgDataContent = `{
			path: '${ path }',
			width: ${ width },
			height: ${ height },
		}`;

	return `export const ${ dashCaseToCamelCase( iconName ) } = {
	get element() {
		const svgData = ${ svgDataContent };

		return iconsManager.createSvgElement( '${ iconName }', svgData );
	},
};`;
}

export function createFrontendIconsFile() {
	const svgIconsJsonPath = resolveFromRoot( 'assets/lib/eicons/eicons.json' );

	if ( ! existsSync( svgIconsJsonPath ) ) {
		return;
	}

	const svgIconsData = JSON.parse( readFileSync( svgIconsJsonPath, 'utf8' ) );

	let svgIconsJSContent = '// This file is automatically generated, please don\'t change anything in this file.\n';
	svgIconsJSContent += getIconsManagerInstanceContent();

	FRONTEND_AVAILABLE_ICONS.forEach( ( iconName ) => {
		svgIconsJSContent += `\n\n${ getIconJSContent( iconName, svgIconsData[ iconName ] ) }`;
	} );

	svgIconsJSContent += '\n';

	writeFileSync(
		resolveFromRoot( 'assets/dev/js/frontend/utils/icons/e-icons.js' ),
		svgIconsJSContent,
	);
}
