name: Run WP Env
description: Runs WP Env environment with Elementor plugin installed and some templates imported.

inputs:
  PHP_VERSION:
    description: PHP version to use.
    default: '7.4'
    required: false
  WP_CORE_VERSION:
    description: WordPress version to use.
    default: 'latest'
    required: false
  PLUGINS:
    description: Relative folders to include as plugins, separated by commas.
    default: ''
    required: false
  PORT:
    description: Port to use for the WP Env environment.
    default: '8888'
    required: false

runs:
  using: "composite"
  steps:
    - name: Update wp-env.json file
      shell: bash
      env:
        PHP_VERSION: ${{ inputs.PHP_VERSION }}
        WP_CORE_VERSION: ${{ inputs.WP_CORE_VERSION }}
        PLUGINS: ${{ inputs.PLUGINS }}
        PORT: ${{ inputs.PORT }}
      run: |
          node ./.github/scripts/build-wp-env.js
    - name: Install wp-env
      shell: bash
      run: |
          npm i -g --no-package-lock --no-save @wordpress/env@5.7.0
    - name: Setup WordPress environment
      shell: bash
      run: |
        npx wp-env start
        # change wp-env folder owner to www-data
        sudo chown 33:33 -R ~/wp-env/
        npx wp-env run cli "bash -c 'bash elementor-config/setup.sh'"
    - name: WordPress debug information
      shell: bash
      run: |
        npx wp-env run cli "wp core version"
        npx wp-env run cli "wp --info"
