import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

import { resolveFromRoot } from './paths.mjs';

const EICONS_JSON = resolveFromRoot( 'assets/lib/eicons/eicons.json' );
const OUTPUT_FILE = resolveFromRoot( 'assets/dev/js/frontend/utils/icons/e-icons.js' );

/**
 * Icons the frontend imports as HTML node elements.
 */
const FRONTEND_AVAILABLE_ICONS = [
	'chevron-left',
	'chevron-right',
	'close',
	'download-bold',
	'facebook',
	'frame-expand',
	'frame-minimize',
	'loading',
	'pinterest',
	'share-arrow',
	'twitter',
	'x-twitter',
	'zoom-in-bold',
	'zoom-out-bold',
];

const HEADER = '// This file is automatically generated, please don\'t change anything in this file.\n';

const MANAGER_INSTANCE = `import IconsManager from './manager';

const iconsManager = new IconsManager( 'eicon' );`;

function dashCaseToCamelCase( value ) {
	return value.replace( /\b-([a-z])/g, ( _, character ) => character.toUpperCase() );
}

function renderIcon( iconName, { path, width, height } ) {
	const svgDataContent = `{
			path: '${ path }',
			width: ${ width },
			height: ${ height },
		}`;

	return `export const ${ dashCaseToCamelCase( iconName ) } = {
	get element() {
		const svgData = ${ svgDataContent };

		return iconsManager.createSvgElement( '${ iconName }', svgData );
	},
};`;
}

/**
 * Regenerates `assets/dev/js/frontend/utils/icons/e-icons.js` from the eicons manifest.
 *
 * The output is a committed source file that the frontend entries import, not a build artifact, so
 * it has to be written before bundling rather than emitted alongside it.
 */
export function generateEiconsFile() {
	if ( ! existsSync( EICONS_JSON ) ) {
		return;
	}

	const icons = JSON.parse( readFileSync( EICONS_JSON, 'utf8' ) );

	const iconModules = FRONTEND_AVAILABLE_ICONS
		.map( ( iconName ) => `\n\n${ renderIcon( iconName, icons[ iconName ] ) }` )
		.join( '' );

	const content = `${ HEADER }${ MANAGER_INSTANCE }${ iconModules }\n`;

	mkdirSync( dirname( OUTPUT_FILE ), { recursive: true } );
	writeFileSync( OUTPUT_FILE, content );
}
