/**
 * The file set copied into `build/` to form the distributable plugin.
 *
 * Order is significant. A positive pattern adds matches and a negative pattern removes them, so the
 * last pattern to match a path decides. The trailing positive entries rely on this to re-include the
 * parts of `vendor` and `core/files/assets` that the broad exclusions above them had removed.
 */
export const PLUGIN_FILE_PATTERNS = [
	'**',
	'!.cursor/**',
	'!.vscode/**',
	'!.git/**',
	'!.github/**',
	'!.run/**',
	'!.gitignore',
	'!.gitmodules',
	'!.jscsrc',
	'!karma.conf.js',
	'!phpcs.xml',
	'!tsconfig.json',
	'!app/**/assets/**',
	'!assets/**/*.map',
	'!assets/dev/**',
	'!assets/js/qunit-tests*',
	'!bin/**',
	'!build/**',
	'!composer.json',
	'!composer.lock',
	'!core/**/assets/**',
	'!cypress.json',
	'!docker-compose.yml',
	'!docs/**',
	'!local-site/**',
	'!modules/**/assets/**',
	'!nightwatch.conf.js',
	'!node_modules/**',
	'!npm-debug.log',
	'!package-lock.json',
	'!package.json',
	'!packages/**',
	'!phpunit.xml',
	'!AGENTS.md',
	'!CHANGELOG.md',
	'!README.md',
	'!ruleset.xml',
	'!tests/**',
	'!test-results/',
	'!tmp/**',
	'!vendor/**',
	'!php-scoper/**',
	'!yarn.lock',
	'!*~',
	'!commitlint.config.js',
	'!scripts/**',
	'!eslint-local-rules.js',
	'!run-on-linux.js',
	'!test*/**',
	'!8888/**',
	'!8889/**',
	'!*.log',
	'!hello-elementor/**',
	'!.env',
	'!Dockerfile',
	'!.dockerignore',

	// Conflict with above rule.
	'core/files/assets/**',
	'vendor/autoload.php',
	'vendor/autoload_packages.php',
	'vendor/composer/**',
	'vendor/elementor/wp-one-package/**',
	'vendor/elementor/wp-notifications-package/**',
	'vendor/elementor/elementor-mcp-composer/**',
	'vendor/jetpack-autoloader/**',
	'vendor/wordpress/**',
];
