name: On Demand Hosting
description: On Demand Hosting

on: 
  workflow_dispatch:
    inputs:
      SITE_URL:
        description: 'The site URL'
        required: true


permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  build-plugin:
    name: Build plugin
    uses: ./.github/workflows/build.yml

  deploy-to-hosting:
    name: Deploy to On Demand Hosting
    runs-on: ubuntu-22.04
    needs: [build-plugin]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-plugin.outputs.artifact_name }}
          path: ./build
      
      - name: Upload to transfer.sh and get public URL
        run: |
          echo "Deploying to site: ${{ inputs.SITE_URL }}"
          echo "Built artifact downloaded to ./build"
          
          # Package the artifact
          cd ./build
          zip -r ../elementor-plugin.zip .
          cd ..
          
          # Upload to transfer.sh and get public URL
          PUBLIC_URL=$(curl --upload-file elementor-plugin.zip https://transfer.sh/elementor-plugin.zip)
          
          echo "Public artifact URL: $PUBLIC_URL"
          echo "PUBLIC_ARTIFACT_URL=$PUBLIC_URL" >> $GITHUB_ENV
          
          # You can now use $PUBLIC_URL or $PUBLIC_ARTIFACT_URL for deployment
          echo "Ready to deploy plugin from public URL to: ${{ inputs.SITE_URL }}"


