import { existsSync, readdirSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';

export function cleanChunkFiles( outputDir, chunkSuffix ) {
	if ( ! existsSync( outputDir ) || ! chunkSuffix ) {
		return;
	}

	for ( const fileName of readdirSync( outputDir ) ) {
		if ( fileName.includes( chunkSuffix ) ) {
			unlinkSync( join( outputDir, fileName ) );
		}
	}
}

export function applyBannerPlugin( banner, { includeCss = false } = {} ) {
	return {
		name: 'apply-banner',
		generateBundle( _, bundle ) {
			for ( const [ fileName, chunk ] of Object.entries( bundle ) ) {
				const isJs = fileName.endsWith( '.js' );
				const isCss = includeCss && fileName.endsWith( '.css' );

				if ( ! isJs && ! isCss ) {
					continue;
				}

				if ( chunk.type === 'chunk' ) {
					chunk.code = `${ banner }\n${ chunk.code }`;
				} else if ( chunk.type === 'asset' && typeof chunk.source === 'string' ) {
					chunk.source = `${ banner }\n${ chunk.source }`;
				}
			}
		},
	};
}

export function appendEntryInitPlugin( initializer ) {
	return {
		name: 'append-entry-init',
		generateBundle( _, bundle ) {
			for ( const [ fileName, chunk ] of Object.entries( bundle ) ) {
				if ( chunk.type !== 'chunk' || ! fileName.endsWith( '.js' ) ) {
					continue;
				}

				const entryName = fileName
					.replace( /\/[^/]+$/, '' )
					.split( '/' )
					.pop()
					?.replace( /\.min\.js$/, '' )
					.replace( /\.js$/, '' );

				if ( ! entryName ) {
					continue;
				}

				const initCode = initializer( entryName );

				if ( initCode ) {
					chunk.code += `\n${ initCode }`;
				}
			}
		},
	};
}

function kebabToCamelCase( kebabCase ) {
	return kebabCase.replace( /-(\w)/g, ( _, char ) => char.toUpperCase() );
}

export function createPackagesInitInitializer() {
	return ( entryName ) => {
		const camelName = kebabToCamelCase( entryName.replace( /\.min$/, '' ) );
		return `window.elementorV2.${ camelName }?.init?.();`;
	};
}

function transformRequestToHandle( request, map ) {
	for ( const item of map ) {
		let { request: requestPattern, handle } = item;
		const regex = requestPattern instanceof RegExp
			? requestPattern
			: new RegExp( `^${ requestPattern }$` );

		if ( regex.test( request ) ) {
			return request.replace( regex, handle );
		}
	}

	return null;
}

function createAssetFileContent( entryHandle, depsHandles ) {
	const depsAsString = depsHandles
		.filter( ( dep ) => dep !== entryHandle )
		.sort()
		.map( ( dep ) => `'${ dep }',` )
		.join( '\n\t\t' );

	return `<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Vite, do not edit it directly.
 */
return [
	'handle' => '${ entryHandle }',
	'deps' => [
		${ depsAsString }
	],
];
`;
}

export function wordpressAssetFilePlugin( {
	handle = ( entryName ) => `elementor-v2-${ entryName }`,
	map = [],
} = {} ) {
	const moduleRequests = new Map();

	return {
		name: 'wordpress-asset-file',
		buildStart() {
			moduleRequests.clear();
		},
		moduleParsed( moduleInfo ) {
			if ( moduleInfo.id ) {
				moduleRequests.set( moduleInfo.id, moduleInfo.importedIds || [] );
			}
		},
		generateBundle( _, bundle ) {
			for ( const [ fileName, chunk ] of Object.entries( bundle ) ) {
				if ( chunk.type !== 'chunk' || ! fileName.endsWith( '.js' ) ) {
					continue;
				}

				const entryName = chunk.name || fileName.replace( /\/[^/]+$/, '' ).split( '/' ).pop()?.replace( /\.min\.js$/, '' ).replace( /\.js$/, '' );

				if ( ! entryName ) {
					continue;
				}

				const depsSet = new Set();

				for ( const moduleId of chunk.moduleIds ) {
					for ( const importedId of moduleRequests.get( moduleId ) || [] ) {
						const depHandle = transformRequestToHandle( importedId, map );

						if ( depHandle ) {
							depsSet.add( depHandle );
						}
					}
				}

				const entryHandle = handle( entryName.replace( /\.min$/, '' ) );
				const assetPath = fileName.replace( /(\.min)?\.js$/i, '.asset.php' );

				this.emitFile( {
					type: 'asset',
					fileName: assetPath,
					source: createAssetFileContent( entryHandle, [ ...depsSet ] ),
				} );
			}
		},
	};
}

export function extractI18nStringsPlugin( { pattern } ) {
	return {
		name: 'extract-i18n-strings',
		async writeBundle( options, bundle ) {
			const { glob } = await import( 'glob' );
			const { writeFile, readFile } = await import( 'node:fs/promises' );
			const { dirname, join, resolve } = await import( 'node:path' );

			const COMMENTS_REGEXPS = [
				/\/\*[\t ]*translators:.*\*\//gm,
				/(\/\/)[\t ]*translators:[^\r\n]*/gm,
			];

			const TRANSLATIONS_REGEXPS = [
				/\b_(?:_|n|nx|x)\(.*?,\s*(?<c>['"`])[\w-]+\k<c>\s*?\)/gs,
			];

			for ( const [ fileName, chunk ] of Object.entries( bundle ) ) {
				if ( chunk.type !== 'chunk' || ! fileName.endsWith( '.min.js' ) ) {
					continue;
				}

				const entryName = chunk.name || fileName.split( '/' ).pop()?.replace( /\.min\.js$/, '' );

				if ( ! entryName ) {
					continue;
				}

				const entryPath = chunk.facadeModuleId ? dirname( chunk.facadeModuleId ) : options.dir;
				const filesPattern = pattern( entryPath, entryName );
				const files = await glob( filesPattern, {
					windowsPathsNoEscape: true,
					ignore: [ '**/node_modules/**' ],
				} );
				const contents = await Promise.all( files.map( ( file ) => readFile( file, 'utf8' ) ) );

				const expressions = contents
					.flatMap( ( content ) => {
						const found = [];

						for ( const regexp of [ ...TRANSLATIONS_REGEXPS, ...COMMENTS_REGEXPS ] ) {
							for ( const match of content.matchAll( regexp ) ) {
								found.push( {
									index: match.index || 0,
									value: match[ 0 ],
									isComment: COMMENTS_REGEXPS.includes( regexp ),
								} );
							}
						}

						return found;
					} )
					.sort( ( a, b ) => a.index - b.index )
					.map( ( item ) => `${ item.value }${ item.isComment ? '' : ';' }` )
					.join( '\n' );

				const stringsPath = join( options.dir, fileName.replace( /\.min\.js$/i, '.strings.js' ) );
				await writeFile( stringsPath, expressions );
			}
		},
	};
}

export function exposePackagesLibraryPlugin() {
	return {
		name: 'expose-packages-library',
		renderChunk( code, chunk ) {
			if ( ! chunk.isEntry ) {
				return null;
			}

			const entryName = chunk.name?.replace( /\.min$/, '' );

			if ( ! entryName ) {
				return null;
			}

			const camelName = kebabToCamelCase( entryName );

			return {
				code: `(function(){${ code }\nwindow.elementorV2=window.elementorV2||{};window.elementorV2.${ camelName }=window.elementorV2.${ camelName }||{};}).call(window);`,
				map: null,
			};
		},
	};
}
