<?php

namespace Elementor\Modules\AtomicWidgets\Documents\Base;

use Elementor\Modules\AtomicWidgets\Parsers\Props_Parser;
use Elementor\Modules\AtomicWidgets\Parsers\Style_Parser;
use Elementor\Modules\AtomicWidgets\PropTypes\Contracts\Prop_Type;
use Elementor\Modules\AtomicWidgets\PropTypes\Primitives\String_Prop_Type;
use Elementor\Modules\AtomicWidgets\PropsResolver\Render_Props_Resolver;
use Elementor\Modules\AtomicWidgets\Styles\Style_Schema;
use Elementor\Modules\Components\PropTypes\Overridable_Prop_Type;
use Elementor\Utils;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

/**
 * Provides atomic v4 schema capabilities to any Document subclass.
 *
 * This trait is the document-level equivalent of Has_Atomic_Base (used by widgets).
 * It intentionally does NOT override get_stack(), get_controls(), get_raw_data(), or
 * get_data_for_save() — those remain untouched so existing Theme Builder panel controls
 * (preview type, HTML tag, conditions) continue to work.
 *
 * Atomic props are stored under a dedicated meta key, separate from
 * _elementor_page_settings, to avoid conflicts with the legacy Controls_Stack flow.
 *
 * Usage:
 *   class My_Atomic_Doc extends Some_Document_Base {
 *       use Has_Atomic_Document;
 *       use Has_Base_Document_Styles;
 *
 *       protected static function define_props_schema(): array { ... }
 *   }
 *
 * @mixin \Elementor\Core\Base\Document
 */
trait Has_Atomic_Document {

	const ATOMIC_SETTINGS_META_KEY = '_elementor_atomic_document_settings';
	const ATOMIC_STYLES_META_KEY   = '_elementor_atomic_document_styles';

	/**
	 * Cached resolved settings (populated lazily on first get_atomic_settings() call).
	 *
	 * @var array
	 */
	private array $atomic_settings_cache = [];

	/**
	 * Cached raw styles (CSS class definitions), populated lazily.
	 *
	 * @var array
	 */
	private array $atomic_styles_cache = [];

	/**
	 * Define the atomic props schema for this document type.
	 * Must be implemented by the concrete class.
	 *
	 * @return array<string, Prop_Type>
	 */
	abstract protected static function define_props_schema(): array;

	/**
	 * Optionally define atomic prop controls that appear in the document settings panel.
	 * The v4 CSS style controls (Layout, Position, etc.) are handled automatically via
	 * the classes prop; this method is only needed for non-CSS document-level settings.
	 *
	 * @return array<\Elementor\Modules\AtomicWidgets\Controls\Section|\Elementor\Modules\AtomicWidgets\Controls\Base\Atomic_Control_Base>
	 */
	protected function define_atomic_controls(): array {
		return [];
	}

	/**
	 * Returns the full props schema, adding the internal _cssid prop and applying filters.
	 * Mirrors Has_Atomic_Base::get_props_schema().
	 *
	 * @return array<string, Prop_Type>
	 */
	public static function get_props_schema(): array {
		$schema           = static::define_props_schema();
		$schema['_cssid'] = String_Prop_Type::make()->meta( Overridable_Prop_Type::ignore() );

		return apply_filters( 'elementor/atomic-widgets/props-schema', $schema );
	}

	/**
	 * Static marker used by Atomic_Document_Base_Styles to detect atomic documents.
	 */
	public static function is_atomic_document(): bool {
		return true;
	}

	/**
	 * Extends get_container_attributes() to apply the v4 CSS class IDs to the document
	 * wrapper element so that instance styles generated by Atomic_Document_Styles take effect.
	 *
	 * All style definitions stored in ATOMIC_STYLES_META_KEY are considered "applied" to the
	 * document root — for documents there is a single editing target, so every persisted style
	 * ID is always active.
	 *
	 * @return array
	 */
	public function get_container_attributes() {
		$attributes = parent::get_container_attributes();

		$initial_class = $attributes['class'] ?? '';
		error_log( '[HasAtomicDocument::get_container_attributes] POST ' . $this->get_main_id() . ' initial class: ' . $initial_class );

		if ( method_exists( $this, 'get_base_styles_dictionary' ) ) {
			$base_style_ids = array_values( $this->get_base_styles_dictionary() );
			error_log( '[HasAtomicDocument::get_container_attributes] base_style_ids: ' . wp_json_encode( $base_style_ids ) );
			if ( ! empty( $base_style_ids ) ) {
				$attributes['class'] .= ' ' . implode( ' ', array_map( 'esc_attr', $base_style_ids ) );
			}
		} else {
			error_log( '[HasAtomicDocument::get_container_attributes] get_base_styles_dictionary method does NOT exist' );
		}

		$style_ids = array_keys( $this->load_atomic_styles() );
		error_log( '[HasAtomicDocument::get_container_attributes] style_ids: ' . wp_json_encode( $style_ids ) );

		if ( ! empty( $style_ids ) ) {
			$attributes['class'] .= ' ' . implode( ' ', array_map( 'esc_attr', $style_ids ) );
		}

		error_log( '[HasAtomicDocument::get_container_attributes] FINAL class: ' . $attributes['class'] );

		return $attributes;
	}

	/**
	 * Extends get_initial_config() to expose atomic document config to the JS editor.
	 * The editor reads elementor.config.document.panel.atomic,
	 * elementor.config.document.panel.atomic_controls, and
	 * elementor.config.document.panel.atomic_props_schema to render the v4 controls panel.
	 *
	 * @return array
	 */
	public function get_initial_config(): array {
		$config = parent::get_initial_config();

		$config['panel']['atomic']             = true;
		$config['panel']['atomic_controls']    = $this->define_atomic_controls();
		$config['panel']['atomic_props_schema'] = static::get_props_schema();
		$config['panel']['atomic_settings']    = $this->load_atomic_settings();
		$config['panel']['atomic_styles']      = $this->load_atomic_styles();

		if ( isset( $config['settings']['controls'] ) ) {
			$config['controls'] = $config['settings']['controls'];
		}

		return $config;
	}

	/**
	 * Intercepts Document::save() to extract and persist atomic props separately.
	 * Handles atomic_settings sent either at the top level of $data (from a direct
	 * atomic document panel save) or nested inside $data['settings'] (from the page
	 * settings model that's included in the standard document save payload).
	 *
	 * @param array $data
	 * @return bool
	 */
	public function save( $data ) {
		// Top-level: sent directly from the atomic document panel.
		if ( isset( $data['atomic_settings'] ) && is_array( $data['atomic_settings'] ) ) {
			$this->save_atomic_settings( $data['atomic_settings'] );
			unset( $data['atomic_settings'] );
		}

		// Nested inside page settings: set by the JS page model before document save.
		if ( isset( $data['settings']['atomic_settings'] ) && is_array( $data['settings']['atomic_settings'] ) ) {
			$this->save_atomic_settings( $data['settings']['atomic_settings'] );
			unset( $data['settings']['atomic_settings'] );
		}

		// CSS class definitions synced by the JS atomic document panel.
		if ( isset( $data['settings']['atomic_styles'] ) && is_array( $data['settings']['atomic_styles'] ) ) {
			$this->save_atomic_styles( $data['settings']['atomic_styles'] );
			unset( $data['settings']['atomic_styles'] );
		}

		return parent::save( $data );
	}

	/**
	 * Returns fully resolved atomic settings for use during template rendering.
	 * Defaults from the schema are applied; values are type-cast and filtered.
	 *
	 * @return array<string, mixed>
	 */
	public function get_atomic_settings(): array {
		$schema = static::get_props_schema();
		$props  = $this->load_atomic_settings();

		return Render_Props_Resolver::for_settings()->resolve( $schema, $props );
	}

	/**
	 * Returns a single resolved atomic setting by key, or null if the key is not in the schema.
	 *
	 * @param string $key
	 * @return mixed|null
	 */
	public function get_atomic_setting( string $key ) {
		$schema = static::get_props_schema();

		if ( ! isset( $schema[ $key ] ) ) {
			return null;
		}

		$settings = $this->get_atomic_settings();

		return $settings[ $key ] ?? null;
	}

	/**
	 * Validates, sanitizes, and persists atomic props to the dedicated meta key.
	 *
	 * @param array $raw_settings Raw settings array from the editor save payload.
	 */
	private function save_atomic_settings( array $raw_settings ): void {
		$parsed = $this->parse_atomic_settings( $raw_settings );
		$this->update_main_meta( self::ATOMIC_SETTINGS_META_KEY, $parsed );
		$this->atomic_settings_cache = $parsed;
	}

	/**
	 * Validates and sanitizes raw settings through Props_Parser against the schema.
	 *
	 * @param array $settings
	 * @return array
	 * @throws \Exception If validation fails.
	 */
	private function parse_atomic_settings( array $settings ): array {
		$schema      = static::get_props_schema();
		$props_parser = Props_Parser::make( $schema );

		$result = $props_parser->parse( $settings );

		if ( ! $result->is_valid() ) {
			throw new \Exception(
				esc_html( 'Atomic document settings validation failed. ' . $result->errors()->to_string() )
			);
		}

		return $result->unwrap();
	}

	/**
	 * Loads atomic settings from post meta, with lazy caching.
	 *
	 * @return array
	 */
	protected function load_atomic_settings(): array {
		if ( ! empty( $this->atomic_settings_cache ) ) {
			return $this->atomic_settings_cache;
		}

		$saved = $this->get_main_meta( self::ATOMIC_SETTINGS_META_KEY );

		$this->atomic_settings_cache = is_array( $saved ) ? $saved : [];

		return $this->atomic_settings_cache;
	}

	/**
	 * Loads raw CSS class definitions from post meta, with lazy caching.
	 * Used by Atomic_Document_Styles to register styles with Atomic_Styles_Manager.
	 *
	 * @return array
	 */
	public function load_atomic_styles(): array {
		if ( ! empty( $this->atomic_styles_cache ) ) {
			return $this->atomic_styles_cache;
		}

		$saved = $this->get_main_meta( self::ATOMIC_STYLES_META_KEY );

		$this->atomic_styles_cache = is_array( $saved ) ? $saved : [];

		return $this->atomic_styles_cache;
	}

	/**
	 * Validates, sanitizes, and persists CSS class definitions to the dedicated meta key.
	 *
	 * @param array $raw_styles Raw styles map from the editor save payload (styleId → styleDef).
	 */
	private function save_atomic_styles( array $raw_styles ): void {
		$parsed = $this->parse_atomic_styles( $raw_styles );
		$this->update_main_meta( self::ATOMIC_STYLES_META_KEY, $parsed );
		$this->atomic_styles_cache = $parsed;
	}

	/**
	 * Validates and sanitizes raw CSS class definitions via Style_Parser.
	 * Mirrors Has_Atomic_Base::parse_atomic_styles().
	 *
	 * @param array $raw_styles
	 * @return array
	 * @throws \Exception If a style definition fails validation.
	 */
	private function parse_atomic_styles( array $raw_styles ): array {
		$style_parser = Style_Parser::make( Style_Schema::get() );
		$parsed       = [];

		foreach ( $raw_styles as $style_id => $style ) {
			$result = $style_parser->parse( $style );

			if ( ! $result->is_valid() ) {
				throw new \Exception(
					esc_html( 'Atomic document style validation failed. ' . $result->errors()->to_string() )
				);
			}

			$parsed[ $style_id ] = $result->unwrap();
		}

		return $parsed;
	}
}
