const config = {
	templates: [
		'accordion',
		'alert',
		'buttons',
		'canvas',
		'container',
		'counter',
		'dividers',
		'global-settings',
		'headings',
		'html',
		'icons',
		'icons-box',
		'icons-list',
		'image',
		'image-box',
		'image-carousel',
		'image-gallery',
		'progress-bar',
		'shortcode',
		'social-icons',
		'spacer',
		'star-rating',
		'tabs',
		'testimonials',
		'text-editor',
		'text-path',
		'toggle',
		'wp-widget-text',
	],
	url_origin: 'http://e3-local-tests:8889',
	tests_viewports: [
		{
			label: 'phone',
			width: 767,
			height: 575,
		},
		{
			label: 'tablet',
			width: 1024,
			height: 768,
		},
		{
			label: 'desktop',
			width: 1366,
			height: 768,
		},
	],
};
module.exports = config;
