name: Check CSS Size Limit

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/config.json'
      - 'bin/**'
      - '.gitignore'
      - 'docs/**'

jobs:
  build-plugin:
     name: Build plugin
     uses: ./.github/workflows/build.yml
  check-size-limit:
    runs-on: ubuntu-latest
    needs: build-plugin
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Check file sizes
        run: node checkFileSize.js
