name: Check CSS Size Limit

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/config.json'
      - 'bin/**'
      - '.gitignore'
      - 'docs/**'

jobs:
  build-plugin:
     name: Build plugin
     uses: ./.github/workflows/build.yml
  check-size-limit:
    runs-on: ubuntu-latest
    needs: build-plugin
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Check CSS File Sizes
        run: |
          # Define size limits
          FRONTEND_CSS_LIMIT=12
          FRONTEND_MIN_CSS_LIMIT=56320

          # Search for all frontend.css and frontend.min.css files
          FRONTEND_CSS_FILES=$(find . -type f -name 'frontend.css')
          FRONTEND_MIN_CSS_FILES=$(find . -type f -name 'frontend.min.css')

          # Check file sizes
          for FILE in $FRONTEND_CSS_FILES; do
            FILE_SIZE=$(stat --printf="%s" "$FILE")
            if [ "$FILE_SIZE" -gt "$FRONTEND_CSS_LIMIT" ]; then
              echo "Error: $FILE exceeds size limit."
              exit 1
            fi
          done

          for FILE in $FRONTEND_MIN_CSS_FILES; do
            FILE_SIZE=$(stat --printf="%s" "$FILE")
            if [ "$FILE_SIZE" -gt "$FRONTEND_MIN_CSS_LIMIT" ]; then
              echo "Error: $FILE exceeds size limit."
              exit 1
            fi
          done

          echo "All files are within size limits."
