name: Update Screenshots

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to update screenshots on'
        required: true
        type: string

jobs:
  update-screenshots:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Run tests to update screenshots
        run: npm run test:playwright:elements-regression:linux -- -u

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: update-screenshots/${{ github.event.inputs.branch }}
          title: 'Update screenshots on ${{ github.event.inputs.branch }}'
          body: |
            This PR updates the screenshot references based on the latest test run.

            Please review the changes carefully before merging.

            Generated by the Update Screenshots workflow.
          commit-message: 'test: update screenshot references'
          base: ${{ github.event.inputs.branch }}
          delete-branch: true
