name: Automated Latest Release

env:
  CHANNEL: 'latest'
  PRERELEASE: 'false'

on:
  pull_request_target:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pull-requests: write

# Cancel in-progress jobs or runs for the current workflow run
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  latest_release:
    if: github.event.pull_request.merged == true && github.base_ref == 'main' && !contains(github.event.pull_request.labels.*.name, 'skip release' )
    permissions: write-all
    runs-on: ubuntu-22.04
    steps:
      - name: checkout branch
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Get Configuration
        id: configuration
        uses: rgarcia-phi/json-to-variables@9835d537368468c4e4de5254dc3efeadda183793
        with:
          filename: './.github/workflows/config.json'
          prefix: config
      - name: Install Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Set POSTFIX value
        id: set_postfix_value
        uses: ./.github/workflows/set-postfix-value
        with:
          PRERELEASE: ${{ env.PRERELEASE }}
      - name: Env Vars Configure
        id: env_vars_configure
        uses: ./.github/workflows/env-vars-configure
        with:
          CHANNEL: ${{ env.CHANNEL }}
          REF: ${{ github.ref }}
          POSTFIX: ${{ steps.set_postfix_value.outputs.postfix }}
      - name: Bump Channel Version
        id: bump_channel_version
        uses: ./.github/workflows/bump-channel-version
        with:
          CLEAN_PACKAGE_VERSION: ${{ env.CLEAN_PACKAGE_VERSION }}
          CHANNEL: ${{ env.CHANNEL }}
          POSTFIX: ${{ steps.set_postfix_value.outputs.postfix }}
          OVERRIDE_PACKAGE_VERSION: true
      - name: Install Dependencies
        uses: ./.github/workflows/install-dependencies
      - name: Build plugin
        uses: ./.github/workflows/build-plugin
        with:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
          BUILD_SCRIPT_PATH: "./.github/scripts/build-zip.sh"
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        with:
          tag_name: ${{ env.PACKAGE_VERSION }}
          target_commitish: ${{ env.CLEAN_REF }}
          files: elementor-*.zip
          body: "Automated release for ${{ env.PACKAGE_VERSION }}"
          prerelease: ${{ env.PRERELEASE }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Post To Slack Created Latest auto Release
        if: ${{ github.event.inputs.pre_release }} == false
        uses: ./.github/workflows/post-to-slack
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_TAG_CHANNELS: ${{ secrets.LATEST_HOSTING_RELEASE_CHANNAL_ID }}
          PAYLOAD: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Hi All :smile:\n\nWe just Published Latest release of *Elementor*\n`${{ env.PACKAGE_VERSION }}`"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Release *${{ env.PACKAGE_VERSION }}* \nCreated by ${{ github.actor }}"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Open :point_left:",
                      "emoji": true
                    },
                    "value": "open-release",
                    "url": "https://github.com/${{ github.repository }}/releases/tag/${{ env.PACKAGE_VERSION }}",
                    "action_id": "button-action"
                  }
                }
              ]
            }

