name: Lint-PHP-Changes-Only

on:
  pull_request:
  merge_group:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  php-file-diff:
    runs-on: ubuntu-22.04
    name: PHP Linter - File Diff
    if: startsWith( github.repository, 'elementor/' )
    permissions:
      pull-requests: read
    steps:
      - name: Get all changed PHP files
        id: changed-php-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **.php
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.php-file-diff.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

  PHP-Linter:
    runs-on: ubuntu-22.04
    needs: [ 'php-file-diff' ]
    if: ${{ needs.php-file-diff.outputs.any_changed == 'true' || github.event.pull_request.title == null }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Run PHP Linter
        env:
          PHP_CHANGED_FILES: ${{ needs.php-file-diff.outputs.all_changed_files }}
        run: |
          for file in ${ PHP_CHANGED_FILES }; do
            echo "$file was changed"
          done
