name: Lint-PHP-Changes-Only

on:
  pull_request:
    paths:
      - '**/*.php'
      - '**/*.twig'
      - '.github/workflows/lint-php-changes-only.yml'
  merge_group:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  php-file-diff:
    runs-on: ubuntu-22.04
    name: PHP Linter - File Diff
    if: startsWith( github.repository, 'elementor/' )
    permissions:
      pull-requests: read
    outputs:
      any_php_changed: ${{ steps.changed-php-files.outputs.any_changed }}
      all_changed_php_files: ${{ steps.changed-php-files.outputs.all_changed_files }}
      any_twig_changed: ${{ steps.changed-twig-files.outputs.any_changed }}
    steps:
      - name: Get all changed PHP files
        id: changed-php-files
        uses: tj-actions/changed-files@v47
        with:
          files: |
            **.php
      - name: Get all changed Twig files
        id: changed-twig-files
        uses: tj-actions/changed-files@v47
        with:
          files: |
            **.twig

  PHP-Linter:
    runs-on: ubuntu-22.04
    needs: ['php-file-diff']
    if: ${{ needs.php-file-diff.outputs.any_php_changed == 'true' || needs.php-file-diff.outputs.any_twig_changed == 'true' || github.event.pull_request.title == null }}
    steps:
      - name: Mask GitHub token
        run: echo "::add-mask::${{ secrets.GITHUB_TOKEN }}"
      - name: Checkout source code
        uses: actions/checkout@v6
      - name: Setup PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Remove Composer GitHub OAuth token
        run: composer config --global --unset github-oauth.github.com || true
      - name: Install Dependencies
        run: |
          composer install
      - name: Run PHP Linter
        if: ${{ needs.php-file-diff.outputs.any_php_changed == 'true' || github.event.pull_request.title == null }}
        env:
          PHP_CHANGED_FILES: ${{ needs.php-file-diff.outputs.all_changed_php_files }}
        run: |
          #composer lint $(echo "${PHP_CHANGED_FILES}" | tr '\n' ' ')
          vendor/bin/phpcs --extensions=php --standard=./ruleset.xml --warning-severity=0 $(echo "${PHP_CHANGED_FILES}" | tr '\n' ' ')
      - name: Twig safety check
        run: composer run check-twig-safety
