name: Mirror to Core Mirror Repository

on:
  push:
    branches:
      - 'main'
  pull_request:  # Run actual mirroring on PR create
    branches:
      - 'main'

permissions:
  contents: read
  # Enable GITHUB_TOKEN to push to repositories
  actions: read
  checks: read
  pull-requests: read

jobs:
  mirror:
    name: Mirror to elementor-core-mirror
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for proper mirroring
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.MAINTAIN_USERNAME }}"
          git config --global user.email "${{ secrets.MAINTAIN_EMAIL }}"

      - name: Setup SSH Key
        run: |
          # Create SSH directory
          mkdir -p ~/.ssh
          
          # Add the deploy key
          echo "${{ secrets.MIRROR_DEPLOY_KEY }}" > ~/.ssh/mirror_deploy_key
          chmod 600 ~/.ssh/mirror_deploy_key
          
          # Add GitHub to known hosts
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          
          # Configure SSH to use the deploy key for github.com
          cat >> ~/.ssh/config << EOF
          Host github.com
            HostName github.com
            User git
            IdentityFile ~/.ssh/mirror_deploy_key
            IdentitiesOnly yes
          EOF

      - name: Mirror to core repository
        run: |
          # Ensure we have the main branch available
          git fetch origin main:main || git checkout -b main origin/main
          
          # Add the mirror repository as a remote (using SSH)
          git remote add mirror git@github.com:elementor/elementor-core-mirror.git
          
          # Push the main branch to the mirror repository
          git push mirror main --force

      - name: Verify mirror status
        run: |
          echo "✅ Successfully mirrored repository to elementor-core-mirror"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Target repository: elementor/elementor-core-mirror"
