name: Mirror to Core Mirror Repository

on:
  push:
    branches:
      - 'main'
  pull_request:  # Run actual mirroring on PR create
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  mirror:
    name: Mirror to elementor-core-mirror
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for proper mirroring
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.MAINTAIN_USERNAME }}"
          git config --global user.email "${{ secrets.MAINTAIN_EMAIL }}"

      - name: Mirror to core repository
        env:
          MIRROR_TOKEN: ${{ secrets.MAINTAIN_TOKEN }}
          TARGET_REPO: "https://github.com/elementor/elementor-core-mirror.git"
        run: |
          # Add the mirror repository as a remote
          git remote add mirror $TARGET_REPO
          
          # Configure authentication for the mirror repository
          git remote set-url mirror https://${MIRROR_TOKEN}@github.com/elementor/elementor-core-mirror.git
          
          # Push the main branch to the mirror repository
          git push mirror main --force

      - name: Verify mirror status
        run: |
          echo "✅ Successfully mirrored repository to elementor-core-mirror"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Target repository: elementor/elementor-core-mirror"
