name: Playwright Test Reusable

on:
  workflow_call:
    inputs:
      build_artifact_name:
        type: string
        required: false
        default: ''

jobs:
  get-php-version:
    name: Calculate PHP Version
    uses: ./.github/workflows/calculate_php_version.yml

  test:
    needs: get-php-version
    runs-on: ubuntu-22.04
    steps:
      - run: echo "reusable ok ${{ needs.get-php-version.outputs.php_version }}"
