name: PR Jira Ticket Check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  pr-jira-ticket:
    name: Jira Ticket
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'elementor/')
    steps:
      - name: Check for Jira ticket
        uses: elementor/elementor-editor-github-actions/actions/pr-jira-ticket@main
