name: Trigger Remote Workflow and Wait

on:
  push:
  pull_request:

jobs:
  trigger_and_wait:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Trigger the remote workflow and wait for its completion
      - name: Trigger remote workflow and wait
        uses: anecdotes-ai/remote-workflow-control@latest
        with:
          github-auth-token: ${{ secrets.MAINTAIN_TOKEN }}
          workflow-org: 'elementor'
          workflow-repo: 'elementor-pro'
          workflow-yaml: 'playwright.yml'
          workflow-branch: 'main'
          workflow-inputs: '{\"event_type\": \"run-from-core\"}'
          wait-timeout-in-minutes: '20'

      # Step 2: Handle success/failure
      - name: Check conclusion
        if: success()
        run: echo "Remote workflow completed successfully!"

      - name: Handle failure
        if: failure()
        run: echo "Remote workflow failed!" && exit 1
