name: Update Screenshots

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to update screenshots on'
        required: true
        type: string
      run_id:
        description: 'Playwright workflow run ID with failed screenshots'
        required: true
        type: string

jobs:
  update-screenshots:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: playwright-test-results-elements-regression
          run-id: ${{ github.event.inputs.run_id }}
          path: test-results
          
      - name: Update screenshots
        run: |
          # Create screenshots directory if it doesn't exist
          mkdir -p tests/elements-regression/screenshots
          
          # Copy actual screenshots to replace linux screenshots
          find test-results -name "*-actual.png" | while read actual; do
            linux_file="tests/elements-regression/screenshots/$(basename "$actual" -actual.png)-linux.png"
            echo "Updating $linux_file"
            cp "$actual" "$linux_file"
          done
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: update-screenshots/${{ github.event.inputs.branch }}
          title: 'Update screenshots on ${{ github.event.inputs.branch }}'
          body: |
            This PR updates the screenshot references based on the failed test results from workflow run #${{ github.event.inputs.run_id }}.
            
            Please review the changes carefully before merging.
            
            Generated by the Update Screenshots workflow.
          commit-message: 'test: update screenshot references'
          base: ${{ github.event.inputs.branch }}
          delete-branch: true 