name: Update Packages Versions

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to get the packages from'
        required: true
        default: 'master'
jobs:
  update-packages-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Run action
        uses: Omerisra6/elementor-editor-github-actions/actions/update-versions-in-elementor@update-elementor-packages-versions
        with:
          target-branch: ${{ github.event.inputs.branch }}
          package-directories: "
            packages
          "
          token: ${{ secrets.ACCESS_TOKEN }}
