name: Update Screenshots

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to update screenshots on'
        required: true
        type: string
      run_id:
        description: 'Playwright workflow run ID with failed screenshots'
        required: true
        type: string

jobs:
  update-screenshots:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: playwright-test-results-elements-regression
          run-id: ${{ github.event.inputs.run_id }}
          path: test-results
          
      - name: Update screenshots
        run: |
          # Create screenshots directory if it doesn't exist
          mkdir -p tests/elements-regression/screenshots
          
          # Initialize associative arrays
          declare -A latest_retries
          declare -A latest_files
          
          echo "Scanning for screenshot files..."
          
          # Find all -actual.png files
          while IFS= read -r actual; do
            test_name=$(basename "$actual" -actual.png)
            test_dir=$(dirname "$actual")
            
            # Extract retry number, default to 0 if not found
            retry_num=$(echo "$test_dir" | grep -o 'retry-[0-9]*' | grep -o '[0-9]*' || echo "0")
            
            echo "Found: $test_name (retry: $retry_num) in $test_dir"
            
            # Update if this is the first occurrence or a later retry
            if [ ! -v latest_retries["$test_name"] ] || [ "$retry_num" -gt "${latest_retries["$test_name"]}" ]; then
              if [ -v latest_retries["$test_name"] ]; then
                echo "  Updating from retry ${latest_retries["$test_name"]} to $retry_num"
              else
                echo "  First occurrence"
              fi
              
              latest_retries["$test_name"]=$retry_num
              latest_files["$test_name"]=$actual
            fi
          done < <(find test-results -name "*-actual.png" | sort -V)
          
          echo -e "\nUpdating screenshot files..."
          
          # Copy only the latest retry for each test
          for test_name in "${!latest_files[@]}"; do
            actual="${latest_files[$test_name]}"
            linux_file="tests/elements-regression/screenshots/$test_name-linux.png"
            
            echo "Processing: $test_name"
            echo "  Source: $actual (retry: ${latest_retries[$test_name]})"
            echo "  Target: $linux_file"
            
            if cp "$actual" "$linux_file"; then
              echo "  ✓ Updated successfully"
            else
              echo "  ✗ Failed to update"
              exit 1
            fi
          done
          
          echo -e "\nSummary:"
          echo "Total screenshots updated: ${#latest_files[@]}"
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: update-screenshots/${{ github.event.inputs.branch }}
          title: 'Update screenshots on ${{ github.event.inputs.branch }}'
          body: |
            This PR updates the screenshot references based on the failed test results from workflow run #${{ github.event.inputs.run_id }}.
            
            ### Summary
            - Source: Workflow run #${{ github.event.inputs.run_id }}
            - Branch: ${{ github.event.inputs.branch }}
            
            Please review the changes carefully before merging. Each screenshot is taken from the last retry of each test, which should represent the most stable state.
            
            Generated by the Update Screenshots workflow.
          commit-message: 'test: update screenshot references'
          base: ${{ github.event.inputs.branch }}
          delete-branch: true 